"""Capability Bootstrap / Preload — "prepare the lesson before the wall".

Why this exists
---------------
Until now V2 could only learn a capability by *hitting the wall*: AUTO fails, the
failure becomes an escalation, a development agent fixes it.  That is the
``LEARN FROM REAL FAILURE`` path and it works, but it is strictly reactive: the
522-row capability catalog has 452 rows the role has never even reached, and no
amount of retrying will ever produce a failure for a route nobody walked.

This module adds the second path, ``PRELOAD BEFORE ENCOUNTER``: continuously scan
the catalog the project already keeps and prepare a *design brief* for the
capabilities that are missing, never tried, defined without an implementation,
covered by an external prior, or sitting on an unwired internal/legacy asset.

What this module is NOT
-----------------------
Not a registry, not a scheduler, not a second development system -- see
``00_MASTER_RULES.md`` §2/§2d.  It is a **projection plus a brief builder**:

* the catalog it scans is ``knowledge/game/capability_catalog.json`` (generated by
  ``tools/build_capability_catalog.py``) and the goal layer is
  ``knowledge/goals/capability_skill_map.json``; it reads both, it owns neither;
* the design drafts it completes are ``skill_factory.PRIORS`` /
  ``dataset/candidate/<SKILL>.json`` -- the existing candidate home;
* in-flight state comes from ``capability_gate.capability_states``, which folds the
  one escalation ledger.  Nothing is stored twice;
* the only thing it *writes* is one escalation record, through
  ``EscalationQueueAdapter.preload()``, into the same ledger, decided by the same
  ``decide()`` throttle, dispatched by the same bridge.  ``PRELOAD`` is an origin,
  not a pipeline.

The two hard ceilings
---------------------
1. **Bootstrap ≠ LIVE_VERIFIED.**  No amount of preparation on this machine can
   promote a capability past ``BOOTSTRAP_MAX_LIFECYCLE``.  Only a production
   episode with a passing verifier does that, in the existing reconciler.
2. **Never an in-flight capability.**  ``WORKING`` / ``DEVELOPMENT_PENDING`` /
   ``CANDIDATE`` / ``LIVE_VERIFY_PENDING`` / ``LIVE_VERIFIED`` are refused by name,
   with the reason recorded, so the same capability cannot be fed to two agents.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence

# ----------------------------------------------------------------- lifecycle

# The ceiling.  A preload may produce a design draft and, at most, a capability
# whose seven fields are complete, whose verifier exists and whose semantics
# resolve -- which is still not evidence, so it is not LIVE_TRIED either.
BOOTSTRAP_MAX_LIFECYCLE = "READY_FOR_LIVE_VERIFY"
FORBIDDEN_LIFECYCLES: tuple[str, ...] = ("LIVE_TRIED", "LIVE_VERIFIED", "STABLE")

# What a preload pass may leave behind, in increasing order of completeness.
NEEDS_LIVE_FRAME = "NEEDS_LIVE_FRAME"       # a design field is UNKNOWN; a probe is owed
DRAFT = "DRAFT"                             # every field has a source, verifier missing
READY_FOR_LIVE_VERIFY = "READY_FOR_LIVE_VERIFY"  # complete + semantics + verifier bound
IN_FLIGHT = "IN_FLIGHT"                     # already in the pipeline; refused by name

BOOTSTRAP_STATES: tuple[str, ...] = (NEEDS_LIVE_FRAME, DRAFT, READY_FOR_LIVE_VERIFY)


def lifecycle_allowed(state: str) -> bool:
    """Guard for anything that writes a lifecycle out of this module.

    Deliberately a function rather than a comment: the operator's rule is
    "Bootstrap 完成 ≠ LIVE_VERIFIED", and a rule that only lives in prose gets
    edited away by the next helpful contributor.
    """
    return state not in FORBIDDEN_LIFECYCLES


# ------------------------------------------------------- why it is a candidate

CLASS_MISSING = "MISSING"
CLASS_NEVER_TRIED = "NEVER_TRIED"
CLASS_DEFINED_NO_IMPLEMENTATION = "DEFINED_NO_IMPLEMENTATION"
CLASS_EXTERNAL_PRIOR_UNIMPLEMENTED = "EXTERNAL_PRIOR_UNIMPLEMENTED"
CLASS_LEGACY_ASSET_UNWIRED = "LEGACY_ASSET_UNWIRED"

BOOTSTRAP_CLASSES: tuple[str, ...] = (
    CLASS_MISSING,
    CLASS_NEVER_TRIED,
    CLASS_DEFINED_NO_IMPLEMENTATION,
    CLASS_EXTERNAL_PRIOR_UNIMPLEMENTED,
    CLASS_LEGACY_ASSET_UNWIRED,
)

CLASS_ZH: dict[str, str] = {
    CLASS_MISSING: "总表里根本没有实现",
    CLASS_NEVER_TRIED: "已实现但从未真机尝试",
    CLASS_DEFINED_NO_IMPLEMENTATION: "有设计草稿但没有实现",
    CLASS_EXTERNAL_PRIOR_UNIMPLEMENTED: "有外部先验但 V2 未实现",
    CLASS_LEGACY_ASSET_UNWIRED: "有 Legacy / 内部资产但未接入",
}

# ----------------------------------------------------------- knowledge ladder

# The operator's order, top first.  Position in this tuple IS the priority, and it
# is the only place that order is written down.
SRC_V2_EVIDENCE = "V2_EVIDENCE"
SRC_LEGACY_ASSET = "LEGACY_ASSET"
SRC_EXTERNAL_MAP = "EXTERNAL_MAP"
SRC_OPEN_SOURCE_UNINDEXED = "OPEN_SOURCE_UNINDEXED"
SRC_GAME_DB_WIKI = "GAME_DB_WIKI"
SRC_SELF_EXPLORATION = "SELF_EXPLORATION"

KNOWLEDGE_LADDER: tuple[str, ...] = (
    SRC_V2_EVIDENCE,
    SRC_LEGACY_ASSET,
    SRC_EXTERNAL_MAP,
    SRC_OPEN_SOURCE_UNINDEXED,
    SRC_GAME_DB_WIKI,
    SRC_SELF_EXPLORATION,
)

SOURCE_ZH: dict[str, str] = {
    SRC_V2_EVIDENCE: "V2 已验收代码 / Knowledge / Episode / Evidence",
    SRC_LEGACY_ASSET: "Legacy 与内部可复用资产（带真实证据）",
    SRC_EXTERNAL_MAP: "knowledge/external/external_capability_map.json",
    SRC_OPEN_SOURCE_UNINDEXED: "成熟开源项目（索引里还没有，需要查源）",
    SRC_GAME_DB_WIKI: "游戏数据库 / Wiki / 攻略",
    SRC_SELF_EXPLORATION: "最后才自行探索（真机探针）",
}


def knowledge_rank(source: str) -> int:
    """1-based position in the ladder; unknown sources sort last."""
    try:
        return KNOWLEDGE_LADDER.index(source) + 1
    except ValueError:
        return len(KNOWLEDGE_LADDER) + 1


# ------------------------------------------------------------- priority ladder

# The operator's development order.  ``REAL_GAP`` is not produced by this scanner
# (real gaps come from episodes, via ``candidates_from_run``) -- it exists here so
# the ladder is complete in one place and the gate can say "a real gap is owed".
PRIO_REAL_GAP = "REAL_GAP"
PRIO_UNLOCKED_MISSING = "UNLOCKED_MISSING"
PRIO_HIGH_FREQ_FREE_VALUE = "HIGH_FREQ_FREE_VALUE"
PRIO_OTHER_UNLOCKED = "OTHER_UNLOCKED"
PRIO_FUTURE_LOCKED = "FUTURE_LOCKED"

PRIORITY_LADDER: tuple[str, ...] = (
    PRIO_REAL_GAP,
    PRIO_UNLOCKED_MISSING,
    PRIO_HIGH_FREQ_FREE_VALUE,
    PRIO_OTHER_UNLOCKED,
    PRIO_FUTURE_LOCKED,
)

PRIORITY_WEIGHT: dict[str, float] = {
    PRIO_REAL_GAP: 100.0,
    PRIO_UNLOCKED_MISSING: 70.0,
    PRIO_HIGH_FREQ_FREE_VALUE: 50.0,
    PRIO_OTHER_UNLOCKED: 30.0,
    PRIO_FUTURE_LOCKED: 10.0,
}

PRIORITY_ZH: dict[str, str] = {
    PRIO_REAL_GAP: "真实运行阻塞 Gap",
    PRIO_UNLOCKED_MISSING: "当前角色已解锁的 MISSING / NEVER_TRIED",
    PRIO_HIGH_FREQ_FREE_VALUE: "高频日常免费价值能力",
    PRIO_OTHER_UNLOCKED: "其它已解锁能力",
    PRIO_FUTURE_LOCKED: "尚未解锁的未来能力",
}

# Risk grades that count as "free value" when claimed by no real-money path.
FREE_RISKS = frozenset({"T0", "T1"})
FREE_BONUS = 8.0

# --------------------------------------------------------------- the 7 fields

FACET_NAMES: tuple[str, ...] = (
    "Preconditions",
    "Navigation",
    "Recognition",
    "Action",
    "Verifier",
    "Recovery",
    "Risk",
)

UNKNOWN = "UNKNOWN"


@dataclass(frozen=True)
class Facet:
    """One of the seven fields the operator requires before a candidate exists.

    ``value`` is what we know; ``source`` names *where* it came from, so a reader
    can tell the difference between "measured on the current client" and "a
    README says so".  ``UNKNOWN`` is a real answer and the common one -- it is the
    honest input to the next live probe, and it is why a plan can never be
    promoted on knowledge alone.
    """

    name: str
    value: str
    source: str = ""
    confidence: float = 0.0

    @property
    def known(self) -> bool:
        return bool(self.value) and self.value != UNKNOWN

    def as_row(self) -> dict[str, Any]:
        return {
            "field": self.name,
            "value": self.value,
            "source": self.source,
            "confidence": round(self.confidence, 3),
        }


@dataclass(frozen=True)
class BootstrapPlan:
    """One catalog row, classified, de-duplicated, ranked and briefed."""

    capability_id: str
    code: str
    goal: str
    skill: str
    classes: tuple[str, ...]
    priority: str
    score: float
    plan_state: str
    knowledge_source: str
    knowledge_rank: int
    facets: tuple[Facet, ...]
    in_flight: str = ""
    in_flight_reason: str = ""
    risk: str = ""
    unlocked: str = "UNKNOWN"
    existing_skill: str = ""
    has_verifier: bool = False
    missing_semantics: tuple[str, ...] = ()
    reuse: Mapping[str, Any] = field(default_factory=dict)
    external: Mapping[str, Any] = field(default_factory=dict)
    maa: Mapping[str, Any] = field(default_factory=dict)
    targeted_test: Mapping[str, Any] = field(default_factory=dict)
    notes: tuple[str, ...] = ()

    @property
    def actionable(self) -> bool:
        return not self.in_flight

    @property
    def unknown_fields(self) -> tuple[str, ...]:
        return tuple(f.name for f in self.facets if not f.known)

    def as_row(self) -> dict[str, Any]:
        return {
            "capability_id": self.capability_id,
            "code": self.code,
            "goal": self.goal,
            "skill": self.skill,
            "classes": list(self.classes),
            "priority": self.priority,
            "score": round(self.score, 2),
            "plan_state": self.plan_state,
            "knowledge_source": self.knowledge_source,
            "knowledge_rank": self.knowledge_rank,
            "unlocked": self.unlocked,
            "risk": self.risk,
            "existing_skill": self.existing_skill,
            "has_verifier": self.has_verifier,
            "missing_semantics": list(self.missing_semantics),
            "in_flight": self.in_flight,
            "in_flight_reason": self.in_flight_reason,
            "unknown_fields": list(self.unknown_fields),
            "facets": [f.as_row() for f in self.facets],
            "reuse": dict(self.reuse),
            "external": dict(self.external),
            "maa": dict(self.maa),
            "targeted_test": dict(self.targeted_test),
            "notes": list(self.notes),
        }

    def markdown(self) -> str:
        lines = [
            f"### {self.capability_id} · {self.code}",
            "",
            f"- 目标：`{self.goal or '-'}`　技能：`{self.skill or '-'}`　风险：`{self.risk or '-'}`",
            f"- 分类：{', '.join(CLASS_ZH.get(c, c) for c in self.classes)}",
            f"- 优先级：{PRIORITY_ZH.get(self.priority, self.priority)}（score {self.score:.1f}）",
            f"- 计划状态：`{self.plan_state}`　知识来源：{SOURCE_ZH.get(self.knowledge_source, self.knowledge_source)}",
        ]
        if self.in_flight:
            lines.append(f"- **拒绝重复 Bootstrap**：{self.in_flight} — {self.in_flight_reason}")
        lines += ["", "| 字段 | 内容 | 来源 | 置信 |", "|---|---|---|---:|"]
        for facet in self.facets:
            lines.append(
                f"| {facet.name} | {facet.value.replace('|', '/')[:220]} | "
                f"{facet.source or '-'} | {facet.confidence:.2f} |"
            )
        if self.targeted_test:
            lines += ["", f"- Targeted Test：`{self.targeted_test.get('name', '-')}` → "
                          f"{self.targeted_test.get('verdict', '-')}（{self.targeted_test.get('detail', '')[:200]}）"]
        return "\n".join(lines)


# ------------------------------------------------------------------- the gate

GATE_OK = "OK"
GATE_NOT_ARMED = "NOT_ARMED_MAIN_LOOP_P0"
GATE_REAL_GAP_WAITING = "REAL_GAP_WAITING"
GATE_AGENT_SLOT_BUSY = "AGENT_SLOT_BUSY"
GATE_DEVICE_LEASED = "DEVICE_LEASED"
GATE_REALTIME_ACTIVITY = "REALTIME_ACTIVITY"
GATE_NOTHING_TO_DO = "NOTHING_TO_DO"

GATE_ZH: dict[str, str] = {
    GATE_OK: "可以低优先级预载",
    GATE_NOT_ARMED: "主闭环 P0 尚未完成，机制已就绪但未启用",
    GATE_REAL_GAP_WAITING: "真实 Gap 还欠队列一次投递，Bootstrap 让路",
    GATE_AGENT_SLOT_BUSY: "唯一开发槽被占用，Bootstrap 不抢",
    GATE_DEVICE_LEASED: "设备正被开发验证持有，Bootstrap 不打扰",
    GATE_REALTIME_ACTIVITY: "V2 正在实时活动（Bear / Rally），Bootstrap 不加负载",
    GATE_NOTHING_TO_DO: "没有可预载的能力",
}


@dataclass(frozen=True)
class PreloadGate:
    allowed: bool
    reason: str
    detail: str = ""
    armed: bool = False

    @property
    def describe(self) -> str:
        return f"{self.reason}: {self.detail}" if self.detail else self.reason


# Activities the operator listed as untouchable: a REALTIME goal is a live fight.
REALTIME_GOALS = frozenset({
    "PARTICIPATE_BEAR", "ALLIANCE_TIMED_EVENTS", "EVENT_MINIMUM_GUARANTEE",
    "AVOID_STAMINA_WASTE",
})
REALTIME_SKILLS = frozenset({"JOIN_RALLY", "START_RALLY", "SCAN_MAP_FOR_BEAST"})

DEFAULT_ARM_PATH = "config/bootstrap_arm.json"
DEFAULT_P0_PATH = "dataset/truth_audit/p0_loop_20260918/P0_LOOP_STATUS.json"


def main_loop_status(root: Path | str | None) -> dict[str, Any]:
    """Read the main autonomous-development loop's own ladder, if it exists.

    The operator's rule is "完成自主开发主闭环 P0 后自动启用该 Bootstrap 机制", so
    this reads the loop's status artifact rather than a flag somebody has to
    remember to flip.  A missing artifact is honestly *not* complete.
    """
    base = Path(root) if root else Path(__file__).resolve().parents[1]
    path = base / DEFAULT_P0_PATH
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return payload if isinstance(payload, dict) else {}


def arm_state(
    root: Path | str | None = None,
    *,
    p0: Mapping[str, Any] | None = None,
) -> tuple[bool, str, str]:
    """``(armed, reason, detail)`` for the preload mechanism.

    Armed means: every stage of the main loop's P0 ladder has reached ``PASS``, so
    the closure the preload feeds has been demonstrated end to end at least once.
    ``config/bootstrap_arm.json`` can override that, explicitly and auditably, so
    an operator can arm it early -- the override is recorded, never silent.
    """
    base = Path(root) if root else Path(__file__).resolve().parents[1]
    ladder = p0 if p0 is not None else main_loop_status(base)
    stages = (ladder or {}).get("stages") or {}
    if stages:
        outstanding = [
            f"{name.split()[0]}={str(body.get('verdict') or '?')}"
            for name, body in stages.items()
            if str((body or {}).get("verdict")) != "PASS"
        ]
        if not outstanding:
            return True, "MAIN_LOOP_P0_PASS", "every stage of the main loop's P0 ladder reads PASS"
        detail = "main loop not fully proven yet: " + ", ".join(outstanding)
    else:
        detail = f"no main-loop status artifact at {DEFAULT_P0_PATH}"

    try:
        override = json.loads((base / DEFAULT_ARM_PATH).read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        override = {}
    if isinstance(override, dict) and override.get("armed"):
        who = str(override.get("armed_by") or "operator")
        why = str(override.get("reason") or "")
        return True, "OPERATOR_OVERRIDE", f"armed by {who}: {why}"

    return False, GATE_NOT_ARMED, detail


def preload_gate(
    *,
    armed: bool,
    arm_reason: str,
    arm_detail: str,
    active_jobs: int,
    pending_records: int,
    lease_holder: str = "",
    runtime: Mapping[str, Any] | None = None,
    actionable: int = 1,
) -> PreloadGate:
    """Whether a preload pass may dispatch anything right now, and why not.

    Pure on purpose: every input is a value some other module already computed, so
    the four things the operator forbids disturbing are visible as four named
    reasons instead of an invisible "we were busy".

    Order matters.  Being unarmed is checked first because it is a statement about
    the whole mechanism, then the four interferences from most severe to least.
    """
    if not armed:
        return PreloadGate(False, arm_reason, arm_detail, armed=False)
    if pending_records > 0:
        return PreloadGate(
            False, GATE_REAL_GAP_WAITING,
            f"{pending_records} record(s) the device already proved are waiting on the queue",
            armed=True,
        )
    if active_jobs > 0:
        return PreloadGate(
            False, GATE_AGENT_SLOT_BUSY,
            f"{active_jobs} development job(s) hold the single slot; a real repair outranks a preload",
            armed=True,
        )
    if lease_holder:
        return PreloadGate(
            False, GATE_DEVICE_LEASED,
            f"the device belongs to {lease_holder}",
            armed=True,
        )
    snapshot = runtime or {}
    goal = str(snapshot.get("current_goal") or "")
    skill = str(snapshot.get("current_skill") or "")
    if goal in REALTIME_GOALS or skill in REALTIME_SKILLS:
        return PreloadGate(
            False, GATE_REALTIME_ACTIVITY,
            f"V2 is running {goal or skill} -- REALTIME, no extra load",
            armed=True,
        )
    if actionable <= 0:
        return PreloadGate(False, GATE_NOTHING_TO_DO, "", armed=True)
    return PreloadGate(True, GATE_OK, "", armed=True)


# ----------------------------------------------------------- small file helpers


def _load_json(path: Path) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def _token_key(text: str) -> str:
    return re.sub(r"[^A-Z0-9]+", "_", str(text).upper()).strip("_")


def _tokens(text: str) -> frozenset[str]:
    return frozenset(t for t in _token_key(text).split("_") if t)


def _moment(value: Any) -> datetime | None:
    if not value:
        return None
    try:
        parsed = datetime.fromisoformat(str(value))
    except (TypeError, ValueError):
        return None
    return parsed if parsed.tzinfo else parsed.replace(tzinfo=timezone.utc)


def _index_by_token(names: Iterable[str]) -> dict[str, tuple[tuple[str, frozenset[str]], ...]]:
    """Token -> ``(name, tokens)`` pairs containing it.

    The corpus is thousands of file names and the catalog is 522 rows; testing
    ``tokens <= name`` for every pair would be ~2.6M set operations per scan.  Every
    name is therefore filed under each of its tokens, and a lookup starts from the
    row's *rarest* token -- the smallest bucket, which is the only one that can
    still be a match anyway.
    """
    index: dict[str, list[tuple[str, frozenset[str]]]] = {}
    for name in names:
        tokens = _tokens(name)
        if not tokens:
            continue
        for token in tokens:
            index.setdefault(token, []).append((str(name), tokens))
    return {token: tuple(bucket) for token, bucket in index.items()}


def _rarest_first(
    tokens: Iterable[str],
    index: Mapping[str, Sequence[tuple[str, frozenset[str]]]],
) -> list[tuple[str, frozenset[str]]]:
    """Candidates to test for one query, smallest bucket first."""
    out: list[tuple[str, frozenset[str]]] = []
    seen: set[str] = set()
    for token in sorted(tokens, key=lambda t: len(index.get(t, ()))):
        for name, name_tokens in index.get(token, ()):
            if name in seen:
                continue
            seen.add(name)
            out.append((name, name_tokens))
    return out


def _contained(
    tokens: frozenset[str],
    index: Mapping[str, Sequence[tuple[str, frozenset[str]]]],
) -> str | None:
    """The first indexed name whose whole token-set contains ``tokens``.

    Every token must appear in **one** name -- "the corpus has something named with
    these words".  A bag-of-tokens search across the whole corpus would match
    almost anything and turn "an asset exists" into noise.
    """
    if not tokens:
        return None
    for token in sorted(tokens, key=lambda t: len(index.get(t, ()))):
        for name, name_tokens in index.get(token, ()):
            if tokens <= name_tokens:
                return name
    return None


# ------------------------------------------------------------------- the scan


class BootstrapScanner:
    """Reads what the project already knows, and says what could be preloaded.

    One instance per pass.  Everything is read once in :meth:`load` -- the catalog
    has 522 rows and the naive version re-read a 300 KB manifest per row.
    """

    def __init__(
        self,
        root: Path | str,
        *,
        catalog: Sequence[Mapping[str, Any]] = (),
        catalog_meta: Mapping[str, Any] | None = None,
        goal_skills: Mapping[str, Any] | None = None,
        registry_states: Mapping[str, str] | None = None,
        registry_ids: Iterable[str] = (),
        cards: Sequence[Mapping[str, Any]] = (),
        drafts: Mapping[str, Mapping[str, Any]] | None = None,
        priors: Mapping[str, Any] | None = None,
        verifier_bindings: Iterable[str] = (),
        registered_semantics: Iterable[str] = (),
        asset_names: Iterable[str] = (),
        ledger_index: Mapping[str, tuple[str, str]] | None = None,
        episodes_attempts: Mapping[str, int] | None = None,
        tools: Mapping[str, Any] | None = None,
        now: datetime | None = None,
    ) -> None:
        self.root = Path(root)
        self.catalog = tuple(catalog)
        self.catalog_meta = dict(catalog_meta or {})
        self.goal_skills = dict(goal_skills or {})
        self.registry_states = dict(registry_states or {})
        self.registry_ids = frozenset(str(x) for x in registry_ids)
        self.cards = tuple(cards)
        self.drafts = {str(k): dict(v) for k, v in (drafts or {}).items()}
        self.priors = dict(priors or {})
        self.verifier_bindings = frozenset(str(x) for x in verifier_bindings)
        self.registered_semantics = frozenset(str(x) for x in registered_semantics)
        self.asset_names = tuple(str(x) for x in asset_names)
        self.ledger_index = dict(ledger_index or {})
        self.episodes_attempts = dict(episodes_attempts or {})
        self.tools = dict(tools or {})
        self.now = now or datetime.now(timezone.utc)
        self._asset_stems = frozenset(_token_key(name) for name in self.asset_names)
        self._asset_index = _index_by_token(self.asset_names)
        self._wiki_index = _index_by_token(
            str(path.relative_to(self.root)).replace("\\", "/")
            for folder in ("knowledge/game", "knowledge/ui", "knowledge/events",
                           "knowledge/alliance", "knowledge/combat", "knowledge/heroes",
                           "knowledge/resources")
            for path in (self.root / folder).glob("*.json")
            if path.is_file()
        )
        self._card_index = self._index_cards()

    # -- construction ------------------------------------------------------

    @classmethod
    def load(
        cls,
        root: Path | str | None = None,
        *,
        ledger_snapshot: Any | None = None,
        policy: Any | None = None,
        now: datetime | None = None,
    ) -> "BootstrapScanner":
        """Read every source once.  Missing files degrade to empty, never raise."""
        base = Path(root) if root else Path(__file__).resolve().parents[1]

        catalog_payload = _load_json(base / "knowledge/game/capability_catalog.json") or {}
        goal_map = _load_json(base / "knowledge/goals/goal_capability_map.json") or {}
        cards = (_load_json(base / "knowledge/external/external_capability_map.json") or {}).get("capabilities") or []
        tools = _load_json(base / "knowledge/tooling/tool_registry.json") or {}

        registry_states: dict[str, str] = {}
        registry_ids: list[str] = []
        try:
            import sys

            if str(base) not in sys.path:
                sys.path.insert(0, str(base))
            from .skills import v2_registry

            for skill in v2_registry().all():
                state = getattr(skill.state, "value", skill.state)
                registry_states[str(skill.id)] = str(state)
                registry_ids.append(str(skill.id))
        except Exception:  # noqa: BLE001 - a scan must not need an importable registry
            pass

        try:
            from .runtime import LiveRuntime

            bindings = tuple(str(k) for k in LiveRuntime.VERIFIED_ATOMIC)
        except Exception:  # noqa: BLE001
            bindings = ()

        from .skill_factory import PRIORS

        drafts: dict[str, Mapping[str, Any]] = {}
        candidate_dir = base / "dataset/candidate"
        if candidate_dir.is_dir():
            for path in sorted(candidate_dir.glob("*.json")):
                payload = _load_json(path)
                if isinstance(payload, dict) and payload.get("lifecycle"):
                    drafts[path.stem] = payload

        manifest = _load_json(base / "dataset/candidate/template_manifest.json") or {}
        semantics = [
            str(row.get("semantic"))
            for row in (manifest.get("records") or [])
            if isinstance(row, Mapping) and row.get("semantic")
        ]

        asset_names: list[str] = []
        for folder in ("dataset/truth_audit", "evidence", "knowledge/skills",
                       "dataset/candidate", "knowledge/failure_patterns"):
            directory = base / folder
            if not directory.is_dir():
                continue
            for path in directory.rglob("*"):
                if path.is_file():
                    asset_names.append(path.name)
        asset_names.append("legacy:" + str(base.parent / "dongri-mumu-bot"))

        ledger_index: dict[str, tuple[str, str]] = {}
        try:
            from .capability_gate import capability_states

            snapshot = ledger_snapshot
            if snapshot is None:
                from .escalation_queue import EscalationLedger, fold

                ledger_path = base / "learning/workbuddy_escalations.jsonl"
                snapshot = fold(EscalationLedger(ledger_path).events())
            if policy is None:
                from .escalation_queue import EscalationPolicy

                policy = EscalationPolicy()
            for record in snapshot.records.values():
                state = capability_states({record.key: record}, now=now or datetime.now(timezone.utc),
                                          policy=policy)
                for capability, (value, reason, _until) in state.items():
                    ledger_index[capability] = (value, reason)
        except Exception:  # noqa: BLE001 - an unreadable ledger means "nothing in flight"
            ledger_index = {}

        attempts: dict[str, int] = {}
        episodes = base / "learning/episodes.jsonl"
        if episodes.is_file():
            try:
                for line in episodes.read_text(encoding="utf-8", errors="replace").splitlines():
                    line = line.strip()
                    if not line.startswith("{"):
                        continue
                    try:
                        row = json.loads(line)
                    except json.JSONDecodeError:
                        continue
                    if not row.get("recorded_at"):
                        continue
                    skill = str(row.get("skill") or "")
                    if skill:
                        attempts[skill] = attempts.get(skill, 0) + 1
            except OSError:
                attempts = {}

        return cls(
            base,
            catalog=catalog_payload.get("capabilities") or (),
            catalog_meta={k: v for k, v in catalog_payload.items() if k != "capabilities"},
            goal_skills=goal_map,
            registry_states=registry_states,
            registry_ids=registry_ids,
            cards=cards,
            drafts=drafts,
            priors=PRIORS,
            verifier_bindings=bindings,
            registered_semantics=semantics,
            asset_names=asset_names,
            ledger_index=ledger_index,
            episodes_attempts=attempts,
            tools=tools,
            now=now,
        )

    # -- indexes -----------------------------------------------------------

    def _index_cards(self) -> dict[str, Mapping[str, Any]]:
        """External cards by the catalog row they name.

        The map's ``v2_equivalent`` is free text (``"CAP-B09/B10 VIP (no skill yet;
        entry never found)"``), so this indexes on the ``CAP-`` ids inside it -- the
        ids are the one machine-readable handhold the map actually has.
        """
        index: dict[str, list[Mapping[str, Any]]] = {}
        for card in self.cards:
            blob = " ".join(
                str(card.get(key) or "")
                for key in ("v2_equivalent", "capability", "current_gap", "implementation_summary")
            )
            for token in set(re.findall(r"CAP-[A-Z]{1,2}\d{1,2}", blob.upper())):
                index.setdefault(token, []).append(card)
        return {k: v[0] for k, v in index.items()}

    def _goal_names_for_skill(self, skill: str) -> tuple[str, ...]:
        """Which goals the project itself says this skill serves."""
        found: list[str] = []
        for goal, body in self.goal_skills.get("goals", {}).items():
            for entry in (body or {}).get("capabilities") or ():
                names = [entry.get("implemented_by"), entry.get("live_verified_by")]
                names += list(entry.get("alternatives") or ())
                if skill and skill in [str(n) for n in names if n]:
                    found.append(str(goal))
        return tuple(dict.fromkeys(found))

    def _sibling_observed(self, category: str) -> bool:
        """Has the role ever shown this feature family?

        The only honest source of "unlocked" this project has: the catalog records
        ``implementation_status``/``lifecycle`` per row, and a family in which at
        least one row has a real live attempt is a family the client has already
        shown.  Everything else stays UNKNOWN -- claiming a feature is unlocked
        because a wiki says so would be prior knowledge outranking evidence.
        """
        for row in self.catalog:
            if str(row.get("category") or "") != category:
                continue
            if str(row.get("implementation_status")) == "EXISTING":
                return True
            if int(row.get("live_attempts") or 0) > 0:
                return True
        return False

    def _match_card(self, row: Mapping[str, Any]) -> Mapping[str, Any]:
        direct = self._card_index.get(str(row.get("capability_id") or "").upper())
        if direct:
            return direct
        code = _tokens(row.get("code"))
        best: Mapping[str, Any] = {}
        best_overlap = 0
        for card in self.cards:
            overlap = len(code & _tokens(card.get("capability") or ""))
            if overlap > best_overlap:
                best, best_overlap = card, overlap
        return best if best_overlap >= 2 else {}

    def _match_draft(self, row: Mapping[str, Any]) -> tuple[str, Mapping[str, Any], bool]:
        """``(skill_id, draft, exact)`` -- the design this row can work from.

        ``exact`` distinguishes "this capability already has a draft" from "a
        *related* capability's draft is informative".  The distinction matters: a
        near-match like ``CLAIM_REWARD`` against ``CLAIM_FREE_REWARD`` gives the seven
        fields something to start from, but it is a hypothesis about a different
        screen, so it may inform a brief and may never make one look designed.
        """
        code = str(row.get("code") or "")
        existing = str(row.get("existing_skill") or "")
        for key in (existing, code):
            if not key:
                continue
            if key in self.drafts:
                return key, self.drafts[key], True
            if key in self.priors:
                return key, {}, True
        # Conservative token match: a multi-token name must be contained in the
        # other, and a single-token name must be the whole other name -- otherwise
        # "RESEARCH" would adopt any skill with the word in it.
        code_tokens = _tokens(code)
        if len(code_tokens) < 2:
            return "", {}, False
        for skill_id in list(self.priors) + list(self.drafts):
            other = _tokens(skill_id)
            if len(other) >= 2 and (other <= code_tokens or code_tokens <= other):
                return skill_id, self.drafts.get(skill_id, {}), False
        return "", {}, False

    # -- classification ----------------------------------------------------

    def _in_flight(self, row: Mapping[str, Any], skill: str) -> tuple[str, str]:
        """The five states that forbid a second Bootstrap, plus the two settled ones.

        Checked against *both* vocabularies -- the catalog's ``code`` and the
        capability layer the ledger speaks -- because the ledger is keyed on the
        capability name from ``capability_skill_map.json`` while the catalog is keyed
        on its own code, and only testing one of them would let the same capability
        reach two agents through two names.
        """
        variants = {
            str(row.get("code") or ""),
            str(row.get("capability_id") or ""),
            skill,
            str(row.get("existing_skill") or ""),
            *self._goal_names_for_skill(skill),
        }
        variants.discard("")
        for name in variants:
            hit = self.ledger_index.get(name)
            if hit:
                state, reason = hit
                if state == "LIVE_VERIFIED":
                    return "LIVE_VERIFIED", reason
                if state == "DEVELOPMENT_PENDING":
                    return "DEVELOPMENT_PENDING", reason
                if state == "COOLDOWN":
                    return "COOLDOWN", f"a job already spent the repair budget: {reason}"
                if state == "BLOCKED":
                    return "BLOCKED", f"already escalated and blocked: {reason}"
                if state == "RUNNABLE" and "live verification" in reason:
                    return "LIVE_VERIFY_PENDING", reason

        for name in (skill, str(row.get("existing_skill") or "")):
            state = self.registry_states.get(name, "")
            if state == "CANDIDATE":
                return "CANDIDATE", f"{name} is a registered candidate awaiting its live try"
            if state == "BLOCKED":
                return "BLOCKED", f"{name} is registered as BLOCKED in the one registry"
            if state in ("VERIFIED", "STABLE"):
                return "LIVE_VERIFIED" if state == "VERIFIED" else "STABLE", (
                    f"{name} is already {state} in the one registry"
                )
        if skill and skill in self.drafts:
            return "CANDIDATE", f"a design draft already exists at dataset/candidate/{skill}.json"
        return "", ""

    def _classes(self, row: Mapping[str, Any], skill: str, card: Mapping[str, Any],
                 draft: Mapping[str, Any], has_prior: bool = False) -> tuple[str, ...]:
        found: list[str] = []
        implemented = str(row.get("implementation_status")) == "EXISTING"
        attempts = int(row.get("live_attempts") or 0)
        if not implemented and not skill:
            if draft or card or has_prior:
                pass  # named by a more specific class below
            else:
                found.append(CLASS_MISSING)
        if implemented and attempts == 0:
            found.append(CLASS_NEVER_TRIED)
        if (draft or has_prior) and not implemented and not skill:
            found.append(CLASS_DEFINED_NO_IMPLEMENTATION)
        if card and not implemented and not skill:
            found.append(CLASS_EXTERNAL_PRIOR_UNIMPLEMENTED)
        if not implemented and not skill and self._has_asset(row):
            found.append(CLASS_LEGACY_ASSET_UNWIRED)
        return tuple(found)

    def _has_asset(self, row: Mapping[str, Any]) -> bool:
        """Is there already an internal/Legacy artefact for this capability?

        Strict on purpose: every token of the catalog code must appear in **one**
        existing file name.  A bag-of-tokens search over the whole corpus matches
        almost everything, and "an asset exists but is unwired" would then mean
        nothing at all.
        """
        tokens = _tokens(row.get("code"))
        if len(tokens) >= 2:
            return bool(_contained(tokens, self._asset_index))
        stem = _token_key(row.get("code"))
        return bool(stem) and stem in self._asset_stems

    def _wiki_files(self, row: Mapping[str, Any]) -> tuple[str, ...]:
        """The in-project game knowledge that should be read before exploring.

        This is ladder rung 5 (game database / wiki / guide), and in this project it
        is a real local corpus -- ``knowledge/game/*.json`` is the canonical map.  A
        pointer is not knowledge, so this never fills a field; it says where the next
        attempt should read, and rung 6 (self-exploration) is only reached when even
        that is empty.
        """
        tokens = _tokens(row.get("code"))
        if not tokens:
            return ()
        found: list[str] = []
        for name, name_tokens in _rarest_first(tokens, self._wiki_index):
            if tokens & name_tokens:
                found.append(name)
            if len(found) >= 3:
                break
        return tuple(found)

    def _priority(self, row: Mapping[str, Any], classes: Sequence[str], unlocked: str) -> str:
        if unlocked != "OBSERVED":
            return PRIO_FUTURE_LOCKED
        risk = str(row.get("risk") or "")
        if not str(row.get("implementation_status")) == "EXISTING":
            return PRIO_UNLOCKED_MISSING
        if risk in FREE_RISKS and str(row.get("real_money_cost")) == "NONE_ALLOWED":
            return PRIO_HIGH_FREQ_FREE_VALUE
        return PRIO_OTHER_UNLOCKED

    # -- facets ------------------------------------------------------------

    def _card_value(self, card: Mapping[str, Any], key: str) -> str:
        value = card.get(key)
        return str(value).strip() if value else ""

    def _facets(
        self,
        row: Mapping[str, Any],
        skill: str,
        card: Mapping[str, Any],
        draft: Mapping[str, Any],
        prior: Any,
    ) -> tuple[Facet, ...]:
        """The operator's seven fields, each with the highest-ranked source that has it.

        Filled in ladder order: V2's own evidence first, then the draft the project
        generated, then Legacy/measured assets, then the external prior.  A field
        with no source stays ``UNKNOWN`` -- and it is the unknown fields that decide
        the plan state, so a brief cannot look complete by being vague.
        """
        goal = ", ".join(self._goal_names_for_skill(skill)) or ""
        verifier_name = ""
        for binding in sorted(self.verifier_bindings):
            if skill and (binding == skill or skill in binding):
                verifier_name = binding
                break
        semantics = tuple(getattr(prior, "required_semantics", ()) or ()) if prior else ()
        semantics = semantics or tuple(str(s) for s in (draft.get("semantic_requirements") or ()))
        missing = tuple(s for s in semantics if s not in self.registered_semantics)

        def pick(*options: tuple[str, str, float]) -> Facet:
            """First option with content wins; the ladder is the argument order."""
            for value, source, confidence in options:
                if value and value != UNKNOWN:
                    return Facet("", value, source, confidence)
            return Facet("", UNKNOWN)

        preconditions = pick(
            (", ".join(str(x) for x in (draft.get("preconditions") or ())),
             SRC_V2_EVIDENCE, 0.6) if draft else ("", "", 0.0),
            (f"从 {', '.join(tuple(getattr(prior, 'entry_pages', ()) or ()))} 出发"
             if prior and getattr(prior, "entry_pages", ()) else "",
             SRC_V2_EVIDENCE, 0.5),
            (self._card_value(card, "preconditions"), SRC_EXTERNAL_MAP, 0.3),
        )
        navigation = pick(
            (" -> ".join(tuple(getattr(prior, "entry_pages", ()) or ())
                        + tuple(getattr(prior, "target_pages", ()) or ()))
             if prior else "", SRC_V2_EVIDENCE, 0.55),
            (self._card_value(card, "navigation"), SRC_EXTERNAL_MAP, 0.45),
            (goal and f"目标 {goal} 的既有路线（见 knowledge/skills）", SRC_GAME_DB_WIKI, 0.3),
        )
        recognition = pick(
            (", ".join(semantics), SRC_V2_EVIDENCE, 0.5 if not missing else 0.3),
            (self._card_value(card, "recognition"), SRC_EXTERNAL_MAP, 0.4),
            (("dataset/truth_audit 与 dataset/candidate 中有同名资产，可先量再设计"
              if self._has_asset(row) else ""), SRC_LEGACY_ASSET, 0.2),
        )
        action = pick(
            (", ".join(str(x) for x in (getattr(prior, "execute_steps", ()) or ())),
             SRC_V2_EVIDENCE, 0.55),
            (self._card_value(card, "action"), SRC_EXTERNAL_MAP, 0.45),
        )
        verifier = pick(
            (f"VERIFIED_ATOMIC[{verifier_name}]" if verifier_name else "", SRC_V2_EVIDENCE, 0.8),
            (", ".join(str(x) for x in (getattr(prior, "success_conditions", ()) or ())),
             SRC_V2_EVIDENCE, 0.4),
            (self._card_value(card, "verification"), SRC_EXTERNAL_MAP, 0.25),
        )
        recovery = pick(
            (", ".join(str(x) for x in (draft.get("recovery") or ())), SRC_V2_EVIDENCE, 0.5),
            (self._card_value(card, "recovery"), SRC_EXTERNAL_MAP, 0.35),
        )
        risk = pick(
            (f"{row.get('risk')}（总表判定，资源成本 {row.get('resource_cost')}）",
             SRC_V2_EVIDENCE, 0.7),
        )
        if self._card_value(card, "reuse_level"):
            risk = Facet(
                risk.name, risk.value,
                f"{risk.source} + {SRC_EXTERNAL_MAP}"
                f"（沿用等级 {card.get('reuse_level')}，许可证 {card.get('license')}）",
                risk.confidence,
            )

        ordered = (preconditions, navigation, recognition, action, verifier, recovery, risk)
        return tuple(
            Facet(name, facet.value, facet.source, facet.confidence)
            for name, facet in zip(FACET_NAMES, ordered)
        )

    # -- the plan ----------------------------------------------------------

    def _maa_check(self, row: Mapping[str, Any]) -> dict[str, Any]:
        """The MAA TOOL CHECK, read from the project's own tool registry.

        The operator's §2b rule is "先找工具，再写代码".  The registry already records
        what is installed and verified, so the check is a lookup rather than a
        rediscovery -- and the answer for anything touching capture / locate /
        click is "MAA", which is also what the row's own ``preferred_backend`` says.
        """
        entries = [t for t in (self.tools.get("tools") or []) if isinstance(t, Mapping)]
        covering = [
            str(t.get("tool_id")) for t in entries
            if str(t.get("tool_id")) in ("MAA_FRAMEWORK", "RAPID_OCR")
            or "OCR" in str(t.get("tool_id")).upper()
            or "RapidOCR" in str(t.get("name"))
        ]
        return {
            "declared_backend": str(row.get("preferred_backend") or ""),
            "covering_tools": covering,
            "custom_code_needed": (
                "模板 / 页面模型 / 锚点 / Verifier 及其证据 —— MAA 只提供引擎，"
                "不提供《无尽冬日》的游戏知识（§2b）"
            ),
            "verdict": "USE_MAA_PLUS_V2_VISION" if covering else "TOOL_REGISTRY_UNREADABLE",
        }

    def _reuse_check(self, row: Mapping[str, Any], skill: str) -> dict[str, Any]:
        """The 2-minute Reuse Check, evaluated from the same five sources.

        Same rule as ``tools/reuse_check.py``: a local route means the external
        search does not happen at all.
        """
        registered = skill in self.registry_ids
        verifier = any(skill and (b == skill or skill in b) for b in self.verifier_bindings)
        draft = skill in self.drafts
        return {
            "skill_registered": registered,
            "verifier_bound": verifier,
            "design_draft": draft,
            "episodes": self.episodes_attempts.get(skill, 0),
            "local_path_exists": bool(verifier and (registered or draft)),
            "verdict": (
                "REUSE_LOCAL" if (verifier and (registered or draft))
                else "NO_LOCAL_PATH_ESCALATE"
            ),
        }

    def _targeted_test(
        self,
        row: Mapping[str, Any],
        skill: str,
        facets: Sequence[Facet],
        missing: Sequence[str],
        verifier_bound: bool,
    ) -> dict[str, Any]:
        """What can be tested *on this machine*, and what cannot.

        Offline the only honest test is design completeness: every field sourced,
        every required semantic registered, a verifier bound.  The live test is
        named too -- and it is not run here, because a preload never touches the
        device (operator §7: Bootstrap is background and low priority).
        """
        unknown = [f.name for f in facets if not f.known]
        design_complete = not unknown and not missing and verifier_bound
        return {
            "name": "DESIGN_COMPLETE",
            "verdict": "PASS" if design_complete else "NOT_PROVEN",
            "detail": (
                "七个字段均有来源、语义已注册、verifier 已绑定"
                if design_complete else
                f"缺字段 {unknown or '-'}；未注册语义 {list(missing) or '-'}；"
                f"verifier {'已绑定' if verifier_bound else '未绑定'}"
            ),
            "live_test_deferred_to": (
                f"run_live.py --goal {', '.join(self._goal_names_for_skill(skill))}"
                if skill and self._goal_names_for_skill(skill)
                else "先取得一帧真机页面（只读探针），再设计缺失的语义"
            ),
        }

    def _plan(self, row: Mapping[str, Any]) -> BootstrapPlan:
        skill = str(row.get("code") or "")
        existing = str(row.get("existing_skill") or "")
        draft_skill, draft, exact = self._match_draft(row)
        skill = existing or draft_skill or skill
        prior = self.priors.get(draft_skill or existing) or self.priors.get(skill)
        card = self._match_card(row)
        classes = self._classes(row, existing, card, draft, has_prior=bool(prior))
        unlocked = "OBSERVED" if (
            str(row.get("current_role_available")) == "OBSERVED_AVAILABLE"
            or self._sibling_observed(str(row.get("category") or ""))
        ) else "UNKNOWN"
        priority = self._priority(row, classes, unlocked)
        facets = self._facets(row, skill, card, draft, prior)
        state, reason = self._in_flight(row, skill)

        semantics = tuple(getattr(prior, "required_semantics", ()) or ()) if prior else ()
        semantics = semantics or tuple(str(s) for s in (draft.get("semantic_requirements") or ()))
        missing = tuple(s for s in semantics if s not in self.registered_semantics)
        verifier_bound = any(skill and (b == skill or skill in b) for b in self.verifier_bindings)
        reuse = self._reuse_check(row, skill)
        maa = self._maa_check(row)
        targeted = self._targeted_test(row, skill, facets, missing, verifier_bound)

        if state:
            plan_state = IN_FLIGHT
        elif any(not f.known for f in facets):
            plan_state = NEEDS_LIVE_FRAME
        elif not exact:
            # Every field came from a *related* capability's draft.  That is a
            # hypothesis about a different screen, so it is a brief, not a design.
            plan_state = NEEDS_LIVE_FRAME
        elif targeted["verdict"] == "PASS":
            plan_state = READY_FOR_LIVE_VERIFY
        else:
            plan_state = DRAFT

        # The knowledge source a preload would actually design *from*.  ``Risk`` is
        # excluded on purpose: it is catalog metadata that every row has, so counting
        # it would rank all 522 rows as "V2 evidence" and make the ladder say nothing.
        # When no field has a source, the ladder still answers -- rung 5 names the
        # in-project knowledge file to read first, rung 6 is the live probe.
        design_sources = [f.source for f in facets if f.name != "Risk" and f.known and f.source]
        wiki = self._wiki_files(row)
        if design_sources:
            knowledge_source = min(design_sources, key=knowledge_rank)
        else:
            knowledge_source = SRC_GAME_DB_WIKI if wiki else SRC_SELF_EXPLORATION

        goal_names = self._goal_names_for_skill(skill)
        # Tier first, then "how cheap is this preload, and how much does it unblock".
        # The tier gap (60 points between the top and bottom rung) is wider than the
        # sum of every bonus below, so the operator's order is preserved and the
        # tie-breaks only order within a rung -- which is why they can be generous.
        score = PRIORITY_WEIGHT.get(priority, 0.0)
        score += float(len(KNOWLEDGE_LADDER) + 1 - knowledge_rank(knowledge_source)) * 6.0
        score += 3.0 * min(len(goal_names), 4)
        if str(row.get("risk")) in FREE_RISKS and str(row.get("real_money_cost")) == "NONE_ALLOWED":
            score += FREE_BONUS
        if classes:
            score += 2.0
        if reuse["verifier_bound"]:
            score += 3.0

        notes: list[str] = []
        if draft_skill and not exact:
            notes.append(
                f"字段来自相近技能 {draft_skill} 的草稿（不是本能力的实现）——必须真机校准后才算设计"
            )
        if wiki and not design_sources:
            notes.append(f"先读项目内知识：{', '.join(wiki)}（第 5 级）；读不到再上真机探针")
        elif not design_sources:
            notes.append("任何一级知识都没有来源 —— 只能先取一帧真机页面（第 6 级，最后手段）")
        if missing:
            notes.append(f"未注册语义 {list(missing)} —— 需要一帧真机页面才能设计（只读探针）")
        if card and str(card.get("reuse_level")) in ("LICENSE_BLOCKED", "NOT_USEFUL"):
            notes.append(f"外部沿用等级 {card.get('reuse_level')}：只作玩法/UI 先验，不复制任何代码")

        return BootstrapPlan(
            capability_id=str(row.get("capability_id") or ""),
            code=str(row.get("code") or ""),
            goal=", ".join(self._goal_names_for_skill(skill)),
            skill=skill,
            classes=classes or (CLASS_MISSING,),
            priority=priority,
            score=score,
            plan_state=plan_state,
            knowledge_source=knowledge_source,
            knowledge_rank=knowledge_rank(knowledge_source),
            facets=facets,
            in_flight=state,
            in_flight_reason=reason,
            risk=str(row.get("risk") or ""),
            unlocked=unlocked,
            existing_skill=existing,
            has_verifier=verifier_bound,
            missing_semantics=missing,
            reuse=reuse,
            external=(
                {
                    "capability": card.get("capability"),
                    "repo": card.get("repo"),
                    "reuse_level": card.get("reuse_level"),
                    "license": card.get("license"),
                    "source_files": list(card.get("source_files") or ())[:4],
                    "current_gap": card.get("current_gap"),
                } if card else {}
            ),
            maa=maa,
            targeted_test=targeted,
            notes=tuple(notes),
        )

    # -- public ------------------------------------------------------------

    def plans(self) -> tuple[BootstrapPlan, ...]:
        return tuple(self._plan(row) for row in self.catalog)

    def candidates(self) -> tuple[BootstrapPlan, ...]:
        """Actionable plans, best first.  The only input to a preload pass."""
        rows = [p for p in self.plans() if p.actionable]
        rows.sort(key=lambda p: (-p.score, p.capability_id))
        return tuple(rows)

    def report(self, *, limit: int = 40) -> dict[str, Any]:
        plans = self.plans()
        actionable = [p for p in plans if p.actionable]
        by_priority: dict[str, int] = {}
        by_state: dict[str, int] = {}
        by_class: dict[str, int] = {}
        by_source: dict[str, int] = {}
        for plan in plans:
            by_priority[plan.priority] = by_priority.get(plan.priority, 0) + 1
            by_state[plan.plan_state] = by_state.get(plan.plan_state, 0) + 1
            by_source[plan.knowledge_source] = by_source.get(plan.knowledge_source, 0) + 1
            for name in plan.classes:
                by_class[name] = by_class.get(name, 0) + 1
        ranked = sorted(actionable, key=lambda p: (-p.score, p.capability_id))
        return {
            "schema_version": "1.0",
            "generated_by": "winter_agent_v2.capability_bootstrap",
            "generated_at": self.now.isoformat(),
            "policy": {
                "max_lifecycle": BOOTSTRAP_MAX_LIFECYCLE,
                "never_from_a_bootstrap": list(FORBIDDEN_LIFECYCLES),
                "knowledge_ladder": list(KNOWLEDGE_LADDER),
                "priority_ladder": list(PRIORITY_LADDER),
                "classes": list(BOOTSTRAP_CLASSES),
                "fields": list(FACET_NAMES),
            },
            "summary": {
                "catalog_rows": len(plans),
                "actionable": len(actionable),
                "in_flight": len(plans) - len(actionable),
                "by_priority": by_priority,
                "by_plan_state": by_state,
                "by_class": by_class,
                "by_knowledge_source": by_source,
            },
            "candidates": [p.as_row() for p in ranked[:limit]],
        }

    def markdown(self, *, limit: int = 12) -> str:
        report = self.report(limit=limit)
        summary = report["summary"]
        lines = [
            "# Capability Bootstrap / Preload —— 候选（自动生成）",
            "",
            "> 本文件由 `winter_agent_v2/capability_bootstrap.py` 扫描 capability_catalog 生成。",
            "> **Bootstrap 完成 ≠ LIVE_VERIFIED**：这里的最高状态是 "
            f"`{BOOTSTRAP_MAX_LIFECYCLE}`，真机验证仍走统一 Development Validation 流程。",
            "",
            f"- 总表行数：{summary['catalog_rows']}　可预载：{summary['actionable']}"
            f"　已在流程中（禁止重复 Bootstrap）：{summary['in_flight']}",
            f"- 按优先级：{summary['by_priority']}",
            f"- 按计划状态：{summary['by_plan_state']}",
            f"- 按来源：{summary['by_knowledge_source']}",
            "",
        ]
        for plan in (self.candidates()[:limit]):
            lines += [plan.markdown(), ""]
        return "\n".join(lines)


# ------------------------------------------------------------------ persistence

BOOTSTRAP_DIR = "learning/capability_bootstrap"
REPORT_JSON = "CANDIDATES.json"
REPORT_MD = "CANDIDATES.md"


def write_report(
    root: Path | str,
    scanner: BootstrapScanner,
    *,
    limit: int = 40,
) -> tuple[Path, Path]:
    """Write the scan where any reader -- panel, agent, operator -- can find it.

    Goes under ``learning/`` because that is the project's machine-state area: this
    is a report about the catalog, not a fifth source of truth about capabilities.
    """
    directory = Path(root) / BOOTSTRAP_DIR
    directory.mkdir(parents=True, exist_ok=True)
    payload = scanner.report(limit=limit)
    json_path = directory / REPORT_JSON
    md_path = directory / REPORT_MD
    json_path.write_text(json.dumps(payload, ensure_ascii=False, indent=1), encoding="utf-8")
    md_path.write_text(scanner.markdown(limit=min(limit, 20)), encoding="utf-8")
    return json_path, md_path


def write_brief(root: Path | str, plan: BootstrapPlan) -> Path:
    """Write one capability's brief as JSON, and return its path.

    This is what a development agent is handed, and it is written **before** the
    record reaches the bridge, so the evidence the assignment names exists on disk
    at the moment the assignment is made.
    """
    directory = Path(root) / BOOTSTRAP_DIR / "briefs"
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / f"{_token_key(plan.code or plan.capability_id)}.json"
    payload = plan.as_row() | {
        "generated_by": "winter_agent_v2.capability_bootstrap",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "max_lifecycle": BOOTSTRAP_MAX_LIFECYCLE,
        "must_not_claim": list(FORBIDDEN_LIFECYCLES),
        "next_flow": (
            "CANDIDATE -> LIVE_VERIFY_PENDING -> DEVELOPMENT_VALIDATION_DEVICE_LEASE -> "
            "new version active -> V2 unified executor (MAA first) -> real device -> "
            "verifier + evidence -> LIVE_VERIFIED -> gameplay pool"
        ),
    }
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=1), encoding="utf-8")
    return path


def work_order_brief(plan: BootstrapPlan) -> str:
    """The brief as the work order's own text.

    Kept short on purpose: the work order is read by a developer agent that will
    spend its timebox in this repository, so it gets the seven fields, the evidence
    that each one came from, and the ceiling it may not cross.
    """
    lines = [
        "PRELOAD BRIEF (prepared before the encounter; no failure led here)",
        f"capability: {plan.capability_id} {plan.code}",
        f"goal: {plan.goal or '(none mapped)'}   skill: {plan.skill or '(none)'}",
        f"classes: {', '.join(plan.classes)}   risk: {plan.risk}   priority: {plan.priority}",
        f"knowledge source ladder rung: {plan.knowledge_rank} {plan.knowledge_source}",
        "",
        "PIPELINE (run it in this order): REUSE CHECK -> EXTERNAL PRIOR -> MAA TOOL CHECK "
        "-> complete the seven fields -> TARGETED TEST -> CANDIDATE",
        f"  reuse check : {plan.reuse.get('verdict')} "
        f"(registered={plan.reuse.get('skill_registered')}, verifier={plan.reuse.get('verifier_bound')}, "
        f"episodes={plan.reuse.get('episodes')})",
        f"  external    : {plan.external.get('capability') or '(no card in the index)'} "
        f"reuse={plan.external.get('reuse_level') or '-'}",
        f"  MAA check   : {plan.maa.get('verdict')} tools={plan.maa.get('covering_tools')}",
        "",
    ]
    for facet in plan.facets:
        lines.append(f"{facet.name}: {facet.value}  [source={facet.source or '-'} conf={facet.confidence:.2f}]")
    if plan.missing_semantics:
        lines.append("")
        lines.append(f"UNREGISTERED SEMANTICS (need a live frame first): {', '.join(plan.missing_semantics)}")
    if plan.external:
        lines.append("")
        lines.append(
            "EXTERNAL PRIOR (prior only -- adapt, never copy; license "
            f"{plan.external.get('license')}, reuse level {plan.external.get('reuse_level')}): "
            f"{plan.external.get('capability')} @ {plan.external.get('repo')}"
        )
        for source in plan.external.get("source_files") or ():
            lines.append(f"  source file: {source}")
    if plan.notes:
        lines.append("")
        lines.extend(f"NOTE: {note}" for note in plan.notes)
    lines += [
        "",
        f"CEILING: the most this work can produce is {BOOTSTRAP_MAX_LIFECYCLE}. "
        "Do not claim LIVE_TRIED / LIVE_VERIFIED / STABLE -- only a production episode "
        "with a passing verifier recorded after this job does, in the reconciler.",
        "SEE ALSO: docs/ADDING_A_LIVE_ROUTE.md (probe -> templates -> wiring -> live verify), "
        "and write any new measurement back into knowledge/external/external_capability_map.json.",
    ]
    return "\n".join(lines)
