"""Runtime pipeline-node generation for Winter Agent OS V2.

Provenance contract — read before extending this module
-------------------------------------------------------
Everything here has to say honestly where it comes from, because the whole point
of V2's evidence discipline is that "generated" is never allowed to mean
"verified". Three sources are mixed in this file and they must stay separable:

1. **TOOL_SHAPED** — the external skill ``maa-pipeline-generate``
   (``scripts/generate_node.py``) produces exactly ONE node kind: an OCR text
   node with the shape
       {"recognition": "OCR", "expected": [...], "roi": [x,y,w,h],
        "action": "Click", "post_delay": 500, "timeout": 2000}
   and nothing else. It reaches the device and the OCR through ``maa_mcp``.
   In this module the frame comes from V2's own device layer under V2's own
   lease and the text comes from ``winter_agent_v2.ocr``, so there is no second
   device chain and no ``maa_mcp`` dependency, but the *emitted schema* is kept
   byte-compatible with what that tool would write.

2. **V2_NATIVE** — the external tool can NOT do any of the following, and this
   module doing them must never be described as the tool doing them:
     - template (image) nodes, including cropping and threshold guessing;
     - validating a node against held-out positive and negative frames;
     - writing into ``knowledge/execution/backend_routing.json`` so the node is
       actually reachable from the executor router;
     - multi-step navigation / ``next`` edges between nodes.
   A node created here is therefore not "generated by the tool"; it is generated
   by V2, shaped like the tool's output where the two overlap.

3. **NOT CLAIMED** — nothing here asserts that a node works on screen. A node
   becomes usable only after :meth:`PipelineAutoGen.validate` has seen it hit
   its positives and miss its negatives on real frames.

Why the frame must come from V2 rather than from the tool's own connect step:
the project rule is one UI owner per device. ``maa_mcp`` would open its own ADB
controller, and two controllers tapping one MuMu instance is exactly the input
collision this designs against.
"""

from __future__ import annotations

import io
import importlib.util
import json
import os
import re
import sys
from contextlib import redirect_stdout
from dataclasses import dataclass, field
from datetime import datetime, timezone
from hashlib import sha1
from pathlib import Path
from typing import Any, Sequence

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_ROUTING_PATH = PROJECT_ROOT / "knowledge" / "execution" / "backend_routing.json"
DEFAULT_TEMPLATE_DIR = PROJECT_ROOT / "dataset" / "candidate" / "autogen"
DEFAULT_GAP_QUEUE_PATH = PROJECT_ROOT / "knowledge" / "execution" / "pipeline_gap_queue.json"

#: MuMu instance V2 actually runs on. Kept as a default only — every caller that
#: already carries a device passes it in, and nothing here dials out on its own.
DEFAULT_SCREEN = (720, 1280)

#: Same default as the external tool (``generate_node.py --expand``).
DEFAULT_EXPAND = 20

#: The external tool's own defaults, reproduced so an OCR node generated here is
#: indistinguishable from one it would have written.
TOOL_DEFAULTS = {"action": "Click", "post_delay": 500, "timeout": 2000}


# --------------------------------------------------------------------- shaping
def _field(token: Any, name: str) -> Any:
    """Read a field from either an ``OCRToken`` dataclass or a plain dict."""
    if isinstance(token, dict):
        return token.get(name)
    return getattr(token, name, None)


def normalize_box(raw: Any) -> list[int] | None:
    """Turn whatever the OCR backend handed back into ``[x, y, w, h]``.

    Two shapes are in circulation and mixing them silently corrupts ROIs:

    * ``[x, y, w, h]`` — what a box-shaped OCR result looks like;
    * four ``(x, y)`` corners — what ``OCRService.recognize`` actually returns today,
      e.g. ``((95,24),(264,24),(264,60),(95,60))`` for 明月的盛典 on the live event
      frame. Read as ``w,h`` that becomes x=95, y=24, w=264, h=60 and every ROI
      built from it lands in the wrong place.

    Returns ``None`` rather than guessing when the shape is neither.
    """
    if raw is None:
        return None
    flat = list(raw)
    if len(flat) == 4 and all(isinstance(v, (int, float)) for v in flat):
        return [int(v) for v in flat]
    if len(flat) == 4 and all(hasattr(v, "__len__") and len(v) == 2 for v in flat):
        xs = [float(v[0]) for v in flat]
        ys = [float(v[1]) for v in flat]
        x, y = min(xs), min(ys)
        return [int(x), int(y), int(max(xs) - x), int(max(ys) - y)]
    return None


def compute_roi(box: Sequence[int], expand: int = DEFAULT_EXPAND,
                screen: tuple[int, int] = DEFAULT_SCREEN) -> list[int]:
    """Expand an OCR box into a ROI, clipped to the screen.

    Arithmetic copied from the external tool's ``compute_roi`` so that a node
    generated here and one generated by ``generate_node.py`` agree pixel for
    pixel. Falls back to the raw box if the expansion collapses the region.
    """
    x, y, w, h = (int(v) for v in box)
    screen_w, screen_h = screen
    roi_x = max(0, x - expand)
    roi_y = max(0, y - expand)
    roi_w = min(screen_w - roi_x, w + 2 * expand)
    roi_h = min(screen_h - roi_y, h + 2 * expand)
    if roi_w <= 0 or roi_h <= 0:
        return [x, y, w, h]
    return [roi_x, roi_y, roi_w, roi_h]


def box_center(box: Sequence[int]) -> tuple[int, int]:
    x, y, w, h = (int(v) for v in box)
    return x + w // 2, y + h // 2


def build_ocr_pipeline_node(text: str, roi: Sequence[int], *, action: str = "Click",
                            post_delay: int = 500, timeout: int = 2000) -> dict[str, Any]:
    """A standard MaaFramework OCR node — TOOL_SHAPED.

    This is the exact dict ``maa-pipeline-generate``'s ``generate_node.py``
    builds (``merge_into_pipeline``'s ``node_config``), so anything that can load
    that tool's output can load this.
    """
    return {
        "recognition": "OCR",
        "expected": [text],
        "roi": [int(v) for v in roi],
        "action": action,
        "post_delay": int(post_delay),
        "timeout": int(timeout),
    }


def build_template_pipeline_node(template: str, roi: Sequence[int] | None = None,
                                 threshold: Sequence[float] = (0.7,)) -> dict[str, Any]:
    """A standard MaaFramework TemplateMatch node — V2_NATIVE.

    The external tool has no image branch at all; this exists because most V2
    controls are icons that carry no legible text and would never be found by an
    OCR node alone.
    """
    node: dict[str, Any] = {"recognition": "TemplateMatch", "template": [template]}
    if roi:
        node["roi"] = [int(v) for v in roi]
    node["threshold"] = [float(t) for t in threshold]
    return node


def build_routing_ocr_node(text: str, roi: Sequence[int]) -> dict[str, Any]:
    """Node shape consumed by ``ExecutorRouter`` — TOOL_SHAPED payload, V2 wiring.

    ``BackendRouter.maa_resolver`` reads ``recognition[semantic]``; a node that
    declares ``"recognition": "OCR"`` must be dispatched to ``MaaExecutorAdapter.ocr``
    rather than to template matching, which is what :func:`dispatch_hint` names.
    """
    node = build_ocr_pipeline_node(text, roi)
    node["kind"] = "OCR"
    return node


def build_routing_template_node(template: str, source_template: str,
                                threshold: Sequence[float] = (0.7, 0.75),
                                roi: Sequence[int] | None = None) -> dict[str, Any]:
    """Node shape consumed by ``ExecutorRouter`` — V2_NATIVE."""
    return {
        "kind": "TEMPLATE",
        "template": template,
        "threshold": [float(t) for t in threshold],
        "source_template": source_template,
        **({"roi": [int(v) for v in roi]} if roi else {}),
    }


def dispatch_hint(node: dict[str, Any]) -> str:
    """Which executor path a node needs. Shared with the router so the two agree."""
    kind = str(node.get("kind", "")).upper()
    if kind == "OCR" or str(node.get("recognition", "")).upper() == "OCR":
        return "OCR"
    if kind == "STRUCTURE":
        return "STRUCTURE"
    return "TEMPLATE"


# ------------------------------------------------------------------ generation
@dataclass(frozen=True)
class GenerationRequest:
    """What to generate, for one semantic, on one skill."""

    semantic: str
    cn_text: str
    skill_id: str
    expand: int = DEFAULT_EXPAND
    #: ``auto`` builds a template node and carries an OCR node alongside it, so a
    #: control found by text still has a text fallback if the icon shifts.
    want: str = "auto"


@dataclass
class GeneratedNode:
    """Result of one generation attempt. Carries its own evidence and its doubts."""

    semantic: str
    skill_id: str
    kind: str
    routing_node: dict[str, Any]
    pipeline_node: dict[str, Any]
    observed_text: str = ""
    observed_score: float = 0.0
    expansion: int = DEFAULT_EXPAND
    template_path: Path | None = None
    frame: Path | None = None
    evidence: dict[str, Any] = field(default_factory=dict)
    #: Set when something is genuinely unsure. Empty for a clean generation.
    warnings: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "semantic": self.semantic,
            "skill_id": self.skill_id,
            "kind": self.kind,
            "routing_node": self.routing_node,
            "pipeline_node": self.pipeline_node,
            "observed_text": self.observed_text,
            "observed_score": self.observed_score,
            "expansion": self.expansion,
            "template_path": str(self.template_path) if self.template_path else None,
            "frame": str(self.frame) if self.frame else None,
            "evidence": self.evidence,
            "warnings": list(self.warnings),
        }


class PipelineAutoGen:
    """Turns "V2 cannot find this control" into a wired, evidenced node.

    The three-step shape came from the external tool (frame -> OCR box -> node);
    everything past writing the node to disk is V2 doing its own work under its
    own device lease.
    """

    def __init__(self, *, device: Any = None, ocr_service: Any = None,
                 project_root: Path = PROJECT_ROOT,
                 routing_path: Path = DEFAULT_ROUTING_PATH,
                 template_dir: Path = DEFAULT_TEMPLATE_DIR,
                 generator_script_path: Path | None = None,
                 screen: tuple[int, int] = DEFAULT_SCREEN) -> None:
        self.device = device
        self.ocr_service = ocr_service
        self.project_root = Path(project_root)
        self.routing_path = Path(routing_path)
        self.template_dir = Path(template_dir)
        self.generator_script_path = Path(generator_script_path) if generator_script_path else (
            self.project_root / ".agents" / "skills" / "maa-pipeline-generate"
            / "scripts" / "generate_node.py"
        )
        self._generator_module: Any = None
        self.screen = screen

    def _tool_node_config(self, text: str, box: Sequence[int], score: float,
                          expand: int) -> tuple[dict[str, Any], list[int]] | None:
        """Call the installed Skill's actual CLI flow without a second device client.

        Its command-line entry point owns its own MaaMCP connection, which V2 must not start
        while AUTO owns the device. V2 injects the box and score obtained from its leased
        capture, captures the node the CLI would merge, and keeps execution, validation, and
        registry writes in the existing runtime.
        """
        script = self.generator_script_path
        if not script.is_file():
            return None
        if self._generator_module is None:
            module_name = "winter_agent_v2_installed_maa_pipeline_generate"
            module_dir = str(script.parent)
            added = module_dir not in sys.path
            if added:
                sys.path.insert(0, module_dir)
            try:
                spec = importlib.util.spec_from_file_location(module_name, script)
                if spec is None or spec.loader is None:
                    return None
                module = importlib.util.module_from_spec(spec)
                sys.modules[module_name] = module
                spec.loader.exec_module(module)
                self._generator_module = module
            finally:
                if added:
                    try:
                        sys.path.remove(module_dir)
                    except ValueError:
                        pass
        compute_roi = getattr(self._generator_module, "compute_roi", None)
        cli_main = getattr(self._generator_module, "main", None)
        if not callable(cli_main):
            return None
        captured: dict[str, Any] = {}
        old_argv = sys.argv
        originals = {
            "connect_device": self._generator_module.connect_device,
            "find_target_box": self._generator_module.find_target_box,
            "merge_into_pipeline": self._generator_module.merge_into_pipeline,
            "resolve_pipeline_path": self._generator_module.resolve_pipeline_path,
        }
        self._generator_module.connect_device = lambda: "V2_CURRENT_DEVICE_LEASE"
        self._generator_module.find_target_box = lambda _controller, _text: (list(box), float(score))
        # The Skill's path helper requires a MaaHub Interface file, while V2 routes nodes
        # through its own existing registry. Resolve the inert capture path locally; the
        # actual generator still builds the node and the capture callback prevents a write.
        self._generator_module.resolve_pipeline_path = lambda path: Path(path)

        def capture_node(_path, _name, node_config, _overwrite):
            captured.update(node_config)
            return "V2_RUNTIME_GENERATED_NODE"

        self._generator_module.merge_into_pipeline = capture_node
        temp_pipeline = self.project_root / "dataset" / "raw" / "autogen" / "runtime_tool_capture.json"
        sys.argv = [
            str(self.generator_script_path), text, "V2RuntimeGeneratedNode", str(temp_pipeline),
            "--expand", str(int(expand)), "--screen-width", str(self.screen[0]),
            "--screen-height", str(self.screen[1]), "--overwrite",
        ]
        try:
            # Call the installed generator's own CLI workflow with V2-supplied OCR and a
            # captured write callback. This runs its argument handling, ROI code, node
            # construction and merge stage, while its MaaMCP device/OCR calls are replaced by
            # V2's already leased frame. The actual pipeline write remains V2's atomic router
            # and Skill Registry update in wire().
            with redirect_stdout(io.StringIO()):
                cli_main()
        except Exception:  # noqa: BLE001 - generator errors fall back without stopping AUTO
            return None
        finally:
            sys.argv = old_argv
            for name, value in originals.items():
                setattr(self._generator_module, name, value)
        roi = captured.get("roi")
        if not isinstance(roi, list) or len(roi) != 4:
            return None
        return captured, [int(value) for value in roi]

    # ---------------------------------------------------------------- inputs
    def ocr(self) -> Any:
        """V2's own OCR, lazily built. Never the external tool's OCR."""
        if self.ocr_service is not None:
            return self.ocr_service
        from winter_agent_v2.ocr import OCRService, RapidOCRBackend

        self.ocr_service = OCRService(RapidOCRBackend())
        return self.ocr_service

    def capture(self, destination: Path) -> Path | None:
        """Grab a frame through the caller's device. Needs no lease of its own."""
        if self.device is None:
            return None
        destination.parent.mkdir(parents=True, exist_ok=True)
        return self.device.screenshot(destination)

    # ------------------------------------------------------------- step 1 & 2
    def tokens_for(self, frame: Path) -> list[Any]:
        """Every OCR token on one frame, read once.

        Harvesting asks the same frame about dozens of labels; running the
        recogniser once per label turns a page visit into minutes of repeat work
        and, worse, into several slightly different readings of one picture.
        """
        result = self.ocr().recognize(Path(frame))
        return list(getattr(result, "tokens", result) or [])

    def locate_in_tokens(self, tokens: list[Any], text: str) -> tuple[list[int], float, str] | None:
        """Highest-confidence token containing ``text``. Mirrors the tool's step 2.

        V2's ``OCRToken`` is a dataclass carrying ``confidence`` where the external
        tool's OCR backend carries ``score``, so both spellings are read -- the same
        tolerance that tool implements in its own ``_val`` helper, for the same
        reason: two different OCR backends, one comparison.
        """
        hits = []
        for token in tokens:
            seen = _field(token, "text")
            if seen and text in str(seen):
                hits.append(token)
        if not hits:
            return None

        def _conf(t: Any) -> float:
            value = _field(t, "score")
            if value is None:
                value = _field(t, "confidence")
            return float(value or 0.0)

        best = max(hits, key=_conf)
        box = normalize_box(_field(best, "box"))
        if box is None:
            return None
        return box, _conf(best), str(_field(best, "text") or "")

    def locate_text(self, frame: Path, text: str) -> tuple[list[int], float, str] | None:
        """One-shot convenience over :meth:`tokens_for` + :meth:`locate_in_tokens`."""
        return self.locate_in_tokens(self.tokens_for(frame), text)

    # ------------------------------------------------------------------ step 3
    def generate(self, request: GenerationRequest, *, frame: Path | None = None,
                 stamp: str | None = None) -> GeneratedNode | None:
        """Generate one node for one control. Returns ``None`` if the text is not on screen.

        Nothing here claims the node works: :meth:`validate` is what decides that.
        """
        if frame is None:
            stamp = stamp or datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
            frame = self.project_root / "dataset" / "raw" / "autogen" / f"{stamp}.png"
            got = self.capture(frame)
            if got is None:
                return None
            frame = got

        found = self.locate_text(frame, request.cn_text)
        if found is None:
            return None
        box, score, observed = found
        roi = compute_roi(box, request.expand, self.screen)
        tool_result = self._tool_node_config(request.cn_text, box, score, request.expand)
        tool_node = tool_result[0] if tool_result is not None else None
        if tool_result is not None:
            roi = tool_result[1]

        warnings: list[str] = []
        if score < 0.9:
            warnings.append(f"OCR score {score:.4f} is below 0.9; the crop may be off")

        want = request.want
        evidence = {
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "source": (
                "installed maa-pipeline-generate CLI + V2 runtime wiring"
                if tool_node is not None else
                "winter_agent_v2.pipeline_autogen V2_NATIVE fallback (generator unavailable)"
            ),
            # Keep the generator's exact OCR output even when V2 chooses a
            # TemplateMatch route that the installed MAA runtime can execute.
            # This separates the tool-produced candidate from the active node.
            "tool_generated_node": tool_node,
            "active_node_source": (
                "INSTALLED_TOOL_OCR" if want == "ocr" and tool_node is not None
                else "V2_NATIVE_TEMPLATE" if want != "ocr" and tool_node is not None
                else "V2_NATIVE_FALLBACK"
            ),
            "generator_tool": str(self.generator_script_path) if tool_node is not None else "",
            "frame": str(frame),
            "observed_text": observed,
            "observed_box": box,
            "ocr_score": round(score, 4),
            "expand": request.expand,
            "validation": "NONE",
        }

        if want == "ocr":
            routing = build_routing_ocr_node(request.cn_text, roi)
            return GeneratedNode(
                semantic=request.semantic, skill_id=request.skill_id, kind="OCR",
                routing_node=routing, pipeline_node=(
                    tool_node or build_ocr_pipeline_node(request.cn_text, roi)
                ),
                observed_text=observed, observed_score=score, expansion=request.expand,
                frame=Path(frame), evidence=evidence, warnings=warnings,
            )

        template_path = self._crop(frame, roi, request.semantic, observed)
        if template_path is None:
            # No template could be cropped, so fall back to the text node the tool
            # would have produced rather than reporting a failure as success.
            warnings.append("template crop unavailable; falling back to OCR node")
            routing = build_routing_ocr_node(request.cn_text, roi)
            return GeneratedNode(
                semantic=request.semantic, skill_id=request.skill_id, kind="OCR",
                routing_node=routing, pipeline_node=(
                    tool_node or build_ocr_pipeline_node(request.cn_text, roi)
                ),
                observed_text=observed, observed_score=score, expansion=request.expand,
                frame=Path(frame), evidence=evidence, warnings=warnings,
            )

        routing = build_routing_template_node(
            request.semantic, _relative(template_path, self.project_root), roi=roi,
        )
        # The template was cropped at exactly this ROI. Matching inside a
        # zero-margin ROI breaks the moment the control drifts a few pixels —
        # measured live: the exploration claim button moved ~30px between
        # 08:01Z and 08:22Z (chest glow animation) and the repair candidate
        # graded NO_MATCH on a frame where the button was plainly visible.
        # Search a generous neighbourhood instead; negative-frame validation
        # guards the extra area against false positives.
        roi = compute_roi(roi, TEMPLATE_ROI_EXPAND, self.screen)
        routing["roi"] = list(roi)
        return GeneratedNode(
            semantic=request.semantic, skill_id=request.skill_id, kind="TEMPLATE",
            routing_node=routing,
            pipeline_node=build_template_pipeline_node(request.semantic, roi),
            observed_text=observed, observed_score=score, expansion=request.expand,
            template_path=template_path, frame=Path(frame), evidence=evidence,
            warnings=warnings,
        )

    def _crop(self, frame: Path, roi: Sequence[int],
              semantic: str, observed: str) -> Path | None:
        """Crop the control out of the frame. V2_NATIVE — the tool has no image path.

        The rect cropped is the *clipped* ROI itself, not box+expand: MAA searches
        inside ``roi`` and rejects a template larger than that region (``templ size
        is too large``), so the two must come from the same rectangle. Near the
        screen edge ``compute_roi`` shrinks, and a crop that ignored that shrink
        produced templates no search region could ever hold.
        """
        try:
            from PIL import Image
        except Exception:
            return None
        left, top, width, height = (int(v) for v in roi)
        right, bottom = left + width, top + height
        digest = sha1(f"{semantic}|{observed}|{left},{top},{right},{bottom}".encode()).hexdigest()[:8]
        dest = self.template_dir / f"{semantic.lower()}__autogen_{digest}.png"
        try:
            dest.parent.mkdir(parents=True, exist_ok=True)
            with Image.open(frame) as im:
                im.convert("RGB").crop((left, top, right, bottom)).save(dest, "PNG")
        except Exception:
            return None
        return dest

    # ------------------------------------------------------------------ wiring
    def wire(self, node: GeneratedNode, *, migration_priority: str = "P3",
             note: str = "") -> tuple[bool, str]:
        """Persist a node into ``backend_routing.json`` so the router can reach it.

        Goes through ``RoutingTable.load``/``save`` rather than hand-editing the
        JSON, because the file also carries ``policy``, ``device`` and
        ``not_migrated``; rewriting it from our own idea of its shape would drop
        another session's unmerged work — the same class of mistake as the
        semantic-dictionary incident.
        """
        from winter_agent_v2.executor_router import RoutingTable

        table = RoutingTable.load(self.routing_path)
        if table.path is None:
            table.path = self.routing_path
        skills = dict(table.skills)
        entry = dict(skills.get(node.skill_id, {}))
        recognition = dict(entry.get("recognition", {}) or {})

        existed = node.semantic in recognition
        recognition[node.semantic] = node.routing_node

        entry["recognition"] = recognition
        entry.setdefault("preferred", "MAA")
        entry.setdefault("fallback", "ADB")
        entry["recognition_backend"] = "MAA"
        # A generated node is wired but NOT promoted: promotion means the corpus
        # gate (>=3 independent live positives, clean negatives) was met, and a
        # harvest-validated node has not earned that. The explicit flag keeps the
        # router's P0 invariant meaningful -- a node cannot drift into "promoted"
        # by an operator forgetting to change a priority letter.
        entry.setdefault("promoted", False)
        # An existing P0/P1 must not be demoted by an autogen write; only raise.
        current = str(entry.get("migration_priority", "P3"))
        entry["migration_priority"] = _higher_priority(current, migration_priority)
        if entry["migration_priority"] == "P0" and not entry.get("promoted", False):
            # Same rule from the other side: never let a priority bump imply a
            # promotion the evidence does not carry.
            entry["migration_priority"] = "P1"

        # Keep the exact MaaFramework node emitted by the installed Skill as an auditable
        # candidate artifact. Runtime execution still uses this same node's V2 routing form,
        # which is what the existing MAA resolver loads; a file's existence alone is never
        # treated as a successful match or a verified Goal.
        pipeline_payload = json.dumps(node.pipeline_node, ensure_ascii=False, indent=2) + "\n"
        digest = sha1(pipeline_payload.encode("utf-8")).hexdigest()[:10]
        pipeline_dir = self.project_root / "dataset" / "raw" / "autogen" / "pipeline_nodes"
        safe_semantic = re.sub(r"[^a-zA-Z0-9_.-]+", "_", node.semantic).strip("._") or "node"
        pipeline_path = pipeline_dir / f"{safe_semantic.lower()}__{digest}.json"
        try:
            pipeline_dir.mkdir(parents=True, exist_ok=True)
            temporary = pipeline_path.with_name(f".{pipeline_path.name}.{os.getpid()}.tmp")
            temporary.write_text(pipeline_payload, encoding="utf-8")
            os.replace(temporary, pipeline_path)
        except OSError as exc:
            return False, f"PIPELINE_NODE_ARTIFACT_WRITE_FAILED:{type(exc).__name__}:{exc}"
        node.evidence["pipeline_node_path"] = _relative(pipeline_path, self.project_root)
        node.evidence["pipeline_node_sha1"] = digest

        # The installed helper produces OCR nodes only. Preserve that exact
        # output as a separate artifact when the active V2 node is a
        # TemplateMatch fallback, so a reviewer can see both the source-tool
        # result and the node the current MAA configuration will execute.
        tool_node = node.evidence.get("tool_generated_node")
        if isinstance(tool_node, dict):
            if tool_node == node.pipeline_node:
                node.evidence["tool_candidate_path"] = _relative(pipeline_path, self.project_root)
                node.evidence["tool_candidate_sha1"] = digest
            else:
                tool_payload = json.dumps(tool_node, ensure_ascii=False, indent=2) + "\n"
                tool_digest = sha1(tool_payload.encode("utf-8")).hexdigest()[:10]
                tool_path = pipeline_dir / f"{safe_semantic.lower()}__tool_ocr__{tool_digest}.json"
                try:
                    temporary = tool_path.with_name(f".{tool_path.name}.{os.getpid()}.tmp")
                    temporary.write_text(tool_payload, encoding="utf-8")
                    os.replace(temporary, tool_path)
                except OSError as exc:
                    return False, f"TOOL_NODE_ARTIFACT_WRITE_FAILED:{type(exc).__name__}:{exc}"
                node.evidence["tool_candidate_path"] = _relative(tool_path, self.project_root)
                node.evidence["tool_candidate_sha1"] = tool_digest
        evidence = dict(entry.get("evidence", {}) or {})
        evidence.update({k: v for k, v in node.evidence.items()})
        evidence["autogen_node_count"] = len(recognition)
        if existed:
            evidence["autogen_overwritten_at"] = node.evidence.get("generated_at", "")
        if note:
            evidence["autogen_note"] = note
        entry["evidence"] = evidence

        skills[node.skill_id] = entry
        table.skills = skills
        table.save()
        return True, ("OVERWROTE" if existed else "CREATED")

    # ---------------------------------------------------------------- evidence
    def validate(self, node: GeneratedNode, *, positives: Sequence[Path],
                 negatives: Sequence[Path] = (), adapter: Any = None) -> dict[str, Any]:
        """Run a node against real frames. Nothing is promoted on generation alone."""
        report: dict[str, Any] = {
            "semantic": node.semantic, "skill_id": node.skill_id, "kind": node.kind,
            "positives": len(positives), "negatives": len(negatives),
            "positive_hits": 0, "negative_hits": 0, "errors": [], "corpus_sufficient": False,
        }
        if adapter is None:
            report["errors"].append("NO_ADAPTER")
            return report
        # Per-frame matcher errors must survive into the report: a repair that
        # graded 0/1 because the adapter was busy or unready used to look
        # identical to a genuine "template not on frame" (measured on
        # BTN_EXPLORATION_IDLE_CLAIM 2026-09-26T08:01Z).
        frame_errors: list[str] = []
        for frame in positives:
            hit, err = self._try_match(adapter, node, Path(frame), expect_hit=True)
            report["positive_hits"] += int(hit)
            if err:
                frame_errors.append(f"positive:{Path(frame).name}:{err}")
        for frame in negatives:
            hit, err = self._try_match(adapter, node, Path(frame), expect_hit=False)
            report["negative_hits"] += int(hit)
            if err and err != "NO_MATCH":
                # a negative frame answering NO_MATCH is the desired outcome,
                # not a matcher failure
                frame_errors.append(f"negative:{Path(frame).name}:{err}")
        if frame_errors:
            report["frame_errors"] = frame_errors
            report["errors"].extend(
                sorted({e.split(":", 2)[2] for e in frame_errors}))
        report["corpus_sufficient"] = (
            len(positives) >= 3 and report["positive_hits"] == len(positives)
            and len(negatives) >= 3 and report["negative_hits"] == 0
        )
        return report

    def _try_match(self, adapter: Any, node: GeneratedNode, frame: Path,
                   expect_hit: bool) -> tuple[bool, str | None]:
        image = self._load_rgb(frame)
        if image is None:
            return False, f"FRAME_UNREADABLE:{frame.name}"
        try:
            if dispatch_hint(node.routing_node) == "OCR":
                results, err = adapter.ocr(
                    image, expected=list(node.routing_node.get("expected", [])),
                    roi=tuple(node.routing_node.get("roi", ()) ) or None,
                )
                if err:
                    return False, err
                return bool(results), None
            images = None
            source = node.routing_node.get("source_template")
            if source:
                src = Path(source)
                if not src.is_absolute():
                    src = self.project_root / src
                if src.is_file():
                    images = {str(node.routing_node.get("template", node.semantic)): src}
            out = adapter.find(
                # The frame is the point of the exercise: validation answers
                # "does this node find the control on THIS picture". Passing
                # ``None`` would make the adapter capture whatever it is looking
                # at right now, so every "positive" would be graded against an
                # unrelated screen and even a perfect template would read 0/1.
                image, node.semantic,
                template=str(node.routing_node.get("template", node.semantic)),
                roi=tuple(node.routing_node.get("roi")) if node.routing_node.get("roi") else None,
                threshold=node.routing_node.get("threshold", 0.7),
                images=images,
            )
            return bool(out.hit), out.error
        except Exception as exc:  # noqa: BLE001
            return False, f"{type(exc).__name__}:{exc}"

    def _load_rgb(self, frame: Path):
        """Read a PNG as the RGB array the adapter expects (``to_rgb_frame`` contract)."""
        try:
            import numpy as np
            from PIL import Image
            with Image.open(frame) as im:
                return np.asarray(im.convert("RGB"))
        except Exception:
            return None


def declared_gap_words(semantic: str, *,
                       queue_path: Path | None = None) -> tuple[str, ...]:
    """The Chinese words the gap queue declares a missing control prints.

    ``knowledge/execution/pipeline_gap_queue.json`` is the reviewed inventory of
    every semantic target that still lacks a recognition node, and each entry
    carries ``visible_words`` -- what the client actually draws there. The
    runtime hook needs exactly that: a *declared* label source for skill-target
    semantics, because the semantic dictionary is keyed by UI-element ids
    (``BTN_*`` / ``PAGE_*``) and -- measured 2026-09-26 -- declares none of the
    81 gap semantics, which is why ``_semantic_cn_text`` returned ``""`` for
    every one of them and the hook never fired (AutoGen = 0 for a whole round).
    This reads the same reviewed words; it invents nothing.

    Only CJK words are returned: the OCR node is built from what OCR can find,
    and the queue's English glosses ("Deploy", "March") are not tokens the
    client's Chinese UI prints as separate text.
    """
    path = queue_path or DEFAULT_GAP_QUEUE_PATH
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return ()
    for item in payload.get("queue") or []:
        if not (isinstance(item, dict) and item.get("semantic") == semantic):
            continue
        words = []
        for word in item.get("visible_words") or ():
            text = str(word).strip()
            if text and any("\u4e00" <= ch <= "\u9fff" for ch in text) and text not in words:
                words.append(text)
        return tuple(words)
    return ()


#: Recognition paths the gap queue's ``recognition.method`` field may declare.
#: OCR and TEMPLATE have real generation paths; COLOR / STRUCTURE / LIST_DYNAMIC
#: are reported as candidates until their executor adapters exist — a declared
#: method without a path is never silently downgraded to a text guess.
#: Extra search margin (pixels) around a template crop. UI controls drift
#: a few dozen px between screens (animated decorations push layouts); a
#: zero-margin ROI turns that drift into a guaranteed NO_MATCH.
TEMPLATE_ROI_EXPAND = 48

GAP_RECOGNITION_METHODS = ("OCR", "TEMPLATE", "COLOR", "STRUCTURE", "LIST_DYNAMIC")


def gap_recognition_method(semantic: str, *,
                           queue_path: Path | None = None) -> str:
    """How the client draws this control, as classified from real UI features.

    Written by ``tools/classify_gap_recognition.py`` into the gap queue. Returns
    ``""`` when the queue says nothing, so callers keep their existing behaviour
    instead of guessing a method.
    """
    path = queue_path or DEFAULT_GAP_QUEUE_PATH
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return ""
    for item in payload.get("queue") or []:
        if not (isinstance(item, dict) and item.get("semantic") == semantic):
            continue
        method = str((item.get("recognition") or {}).get("method", "")).upper()
        return method if method in GAP_RECOGNITION_METHODS else ""
    return ""


def build_color_pipeline_node(roi: Sequence[int]) -> dict[str, Any]:
    """MAA ColorMatch node shape — V2_NATIVE, candidate-only until an adapter runs it."""
    return {"recognition": "ColorMatch", "roi": [int(v) for v in roi],
            "order": 0, "action": "Click"}


DEFAULT_REPAIR_EVENTS_PATH = PROJECT_ROOT / "learning" / "autogen_repair_events.jsonl"


def record_repair_event(semantic: str, skill_id: str, *, stage: str, detail: str = "",
                        page: str = "", failure_type: str = "",
                        extra: dict[str, Any] | None = None) -> None:
    """Append one AutoRepair lifecycle event, skips included.

    The repair hook is bounded and conditional, so "AutoRepair = 0" can mean
    five different things. Every skip reason (NO_DECLARED_TEXT, NO_FRAME,
    ALREADY_ATTEMPTED_THIS_ROUND, ...) is recorded here so the next diagnosis
    reads one jsonl instead of re-deriving the branch conditions. A record
    failure must never break a production run.
    """
    try:
        record = {
            "recorded_at": datetime.now(timezone.utc).isoformat(),
            "semantic": semantic, "skill_id": skill_id, "stage": stage,
            "detail": detail, "page": page, "failure_type": failure_type,
        }
        if extra:
            record.update(extra)
        path = Path(os.environ.get("WINTER_REPAIR_EVENTS_PATH", DEFAULT_REPAIR_EVENTS_PATH))
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("a", encoding="utf-8") as fh:
            fh.write(json.dumps(record, ensure_ascii=False) + "\n")
    except Exception:  # noqa: BLE001 - observability must never stop AUTO
        pass


def _relative(path: Path, root: Path) -> str:
    try:
        return str(Path(path).resolve().relative_to(Path(root).resolve())).replace("\\", "/")
    except ValueError:
        return str(path)


def _higher_priority(current: str, new: str) -> str:
    """Keep the more urgent of two priorities so autogen can never demote a node."""
    try:
        return current if int(current[1:]) <= int(new[1:]) else new
    except (ValueError, IndexError):
        return current
