"""Runtime pipeline-node generation for Winter Agent OS V2.

Provenance contract — read before extending this module
-------------------------------------------------------
Everything here has to say honestly where it comes from, because the whole point
of V2's evidence discipline is that "generated" is never allowed to mean
"verified". Three sources are mixed in this file and they must stay separable:

1. **TOOL_SHAPED** — the external skill ``maa-pipeline-generate``
   (``scripts/generate_node.py``) produces exactly ONE node kind: an OCR text
   node with the shape
       {"recognition": "OCR", "expected": [...], "roi": [x,y,w,h],
        "action": "Click", "post_delay": 500, "timeout": 2000}
   and nothing else. It reaches the device and the OCR through ``maa_mcp``.
   In this module the frame comes from V2's own device layer under V2's own
   lease and the text comes from ``winter_agent_v2.ocr``, so there is no second
   device chain and no ``maa_mcp`` dependency, but the *emitted schema* is kept
   byte-compatible with what that tool would write.

2. **V2_NATIVE** — the external tool can NOT do any of the following, and this
   module doing them must never be described as the tool doing them:
     - template (image) nodes, including cropping and threshold guessing;
     - validating a node against held-out positive and negative frames;
     - writing into ``knowledge/execution/backend_routing.json`` so the node is
       actually reachable from the executor router;
     - multi-step navigation / ``next`` edges between nodes.
   A node created here is therefore not "generated by the tool"; it is generated
   by V2, shaped like the tool's output where the two overlap.

3. **NOT CLAIMED** — nothing here asserts that a node works on screen. A node
   becomes usable only after :meth:`PipelineAutoGen.validate` has seen it hit
   its positives and miss its negatives on real frames.

Why the frame must come from V2 rather than from the tool's own connect step:
the project rule is one UI owner per device. ``maa_mcp`` would open its own ADB
controller, and two controllers tapping one MuMu instance is exactly the input
collision this designs against.
"""

from __future__ import annotations

import io
import json
from dataclasses import dataclass, field
from datetime import datetime, timezone
from hashlib import sha1
from pathlib import Path
from typing import Any, Sequence

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_ROUTING_PATH = PROJECT_ROOT / "knowledge" / "execution" / "backend_routing.json"
DEFAULT_TEMPLATE_DIR = PROJECT_ROOT / "dataset" / "candidate" / "autogen"

#: MuMu instance V2 actually runs on. Kept as a default only — every caller that
#: already carries a device passes it in, and nothing here dials out on its own.
DEFAULT_SCREEN = (720, 1280)

#: Same default as the external tool (``generate_node.py --expand``).
DEFAULT_EXPAND = 20

#: The external tool's own defaults, reproduced so an OCR node generated here is
#: indistinguishable from one it would have written.
TOOL_DEFAULTS = {"action": "Click", "post_delay": 500, "timeout": 2000}


# --------------------------------------------------------------------- shaping
def _field(token: Any, name: str) -> Any:
    """Read a field from either an ``OCRToken`` dataclass or a plain dict."""
    if isinstance(token, dict):
        return token.get(name)
    return getattr(token, name, None)


def normalize_box(raw: Any) -> list[int] | None:
    """Turn whatever the OCR backend handed back into ``[x, y, w, h]``.

    Two shapes are in circulation and mixing them silently corrupts ROIs:

    * ``[x, y, w, h]`` — what a box-shaped OCR result looks like;
    * four ``(x, y)`` corners — what ``OCRService.recognize`` actually returns today,
      e.g. ``((95,24),(264,24),(264,60),(95,60))`` for 明月的盛典 on the live event
      frame. Read as ``w,h`` that becomes x=95, y=24, w=264, h=60 and every ROI
      built from it lands in the wrong place.

    Returns ``None`` rather than guessing when the shape is neither.
    """
    if raw is None:
        return None
    flat = list(raw)
    if len(flat) == 4 and all(isinstance(v, (int, float)) for v in flat):
        return [int(v) for v in flat]
    if len(flat) == 4 and all(hasattr(v, "__len__") and len(v) == 2 for v in flat):
        xs = [float(v[0]) for v in flat]
        ys = [float(v[1]) for v in flat]
        x, y = min(xs), min(ys)
        return [int(x), int(y), int(max(xs) - x), int(max(ys) - y)]
    return None


def compute_roi(box: Sequence[int], expand: int = DEFAULT_EXPAND,
                screen: tuple[int, int] = DEFAULT_SCREEN) -> list[int]:
    """Expand an OCR box into a ROI, clipped to the screen.

    Arithmetic copied from the external tool's ``compute_roi`` so that a node
    generated here and one generated by ``generate_node.py`` agree pixel for
    pixel. Falls back to the raw box if the expansion collapses the region.
    """
    x, y, w, h = (int(v) for v in box)
    screen_w, screen_h = screen
    roi_x = max(0, x - expand)
    roi_y = max(0, y - expand)
    roi_w = min(screen_w - roi_x, w + 2 * expand)
    roi_h = min(screen_h - roi_y, h + 2 * expand)
    if roi_w <= 0 or roi_h <= 0:
        return [x, y, w, h]
    return [roi_x, roi_y, roi_w, roi_h]


def box_center(box: Sequence[int]) -> tuple[int, int]:
    x, y, w, h = (int(v) for v in box)
    return x + w // 2, y + h // 2


def build_ocr_pipeline_node(text: str, roi: Sequence[int], *, action: str = "Click",
                            post_delay: int = 500, timeout: int = 2000) -> dict[str, Any]:
    """A standard MaaFramework OCR node — TOOL_SHAPED.

    This is the exact dict ``maa-pipeline-generate``'s ``generate_node.py``
    builds (``merge_into_pipeline``'s ``node_config``), so anything that can load
    that tool's output can load this.
    """
    return {
        "recognition": "OCR",
        "expected": [text],
        "roi": [int(v) for v in roi],
        "action": action,
        "post_delay": int(post_delay),
        "timeout": int(timeout),
    }


def build_template_pipeline_node(template: str, roi: Sequence[int] | None = None,
                                 threshold: Sequence[float] = (0.7,)) -> dict[str, Any]:
    """A standard MaaFramework TemplateMatch node — V2_NATIVE.

    The external tool has no image branch at all; this exists because most V2
    controls are icons that carry no legible text and would never be found by an
    OCR node alone.
    """
    node: dict[str, Any] = {"recognition": "TemplateMatch", "template": [template]}
    if roi:
        node["roi"] = [int(v) for v in roi]
    node["threshold"] = [float(t) for t in threshold]
    return node


def build_routing_ocr_node(text: str, roi: Sequence[int]) -> dict[str, Any]:
    """Node shape consumed by ``ExecutorRouter`` — TOOL_SHAPED payload, V2 wiring.

    ``BackendRouter.maa_resolver`` reads ``recognition[semantic]``; a node that
    declares ``"recognition": "OCR"`` must be dispatched to ``MaaExecutorAdapter.ocr``
    rather than to template matching, which is what :func:`dispatch_hint` names.
    """
    node = build_ocr_pipeline_node(text, roi)
    node["kind"] = "OCR"
    return node


def build_routing_template_node(template: str, source_template: str,
                                threshold: Sequence[float] = (0.7, 0.75),
                                roi: Sequence[int] | None = None) -> dict[str, Any]:
    """Node shape consumed by ``ExecutorRouter`` — V2_NATIVE."""
    return {
        "kind": "TEMPLATE",
        "template": template,
        "threshold": [float(t) for t in threshold],
        "source_template": source_template,
        **({"roi": [int(v) for v in roi]} if roi else {}),
    }


def dispatch_hint(node: dict[str, Any]) -> str:
    """Which executor path a node needs. Shared with the router so the two agree."""
    kind = str(node.get("kind", "")).upper()
    if kind == "OCR" or str(node.get("recognition", "")).upper() == "OCR":
        return "OCR"
    return "TEMPLATE"


# ------------------------------------------------------------------ generation
@dataclass(frozen=True)
class GenerationRequest:
    """What to generate, for one semantic, on one skill."""

    semantic: str
    cn_text: str
    skill_id: str
    expand: int = DEFAULT_EXPAND
    #: ``auto`` builds a template node and carries an OCR node alongside it, so a
    #: control found by text still has a text fallback if the icon shifts.
    want: str = "auto"


@dataclass
class GeneratedNode:
    """Result of one generation attempt. Carries its own evidence and its doubts."""

    semantic: str
    skill_id: str
    kind: str
    routing_node: dict[str, Any]
    pipeline_node: dict[str, Any]
    observed_text: str = ""
    observed_score: float = 0.0
    expansion: int = DEFAULT_EXPAND
    template_path: Path | None = None
    frame: Path | None = None
    evidence: dict[str, Any] = field(default_factory=dict)
    #: Set when something is genuinely unsure. Empty for a clean generation.
    warnings: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "semantic": self.semantic,
            "skill_id": self.skill_id,
            "kind": self.kind,
            "routing_node": self.routing_node,
            "pipeline_node": self.pipeline_node,
            "observed_text": self.observed_text,
            "observed_score": self.observed_score,
            "expansion": self.expansion,
            "template_path": str(self.template_path) if self.template_path else None,
            "frame": str(self.frame) if self.frame else None,
            "evidence": self.evidence,
            "warnings": list(self.warnings),
        }


class PipelineAutoGen:
    """Turns "V2 cannot find this control" into a wired, evidenced node.

    The three-step shape came from the external tool (frame -> OCR box -> node);
    everything past writing the node to disk is V2 doing its own work under its
    own device lease.
    """

    def __init__(self, *, device: Any = None, ocr_service: Any = None,
                 project_root: Path = PROJECT_ROOT,
                 routing_path: Path = DEFAULT_ROUTING_PATH,
                 template_dir: Path = DEFAULT_TEMPLATE_DIR,
                 screen: tuple[int, int] = DEFAULT_SCREEN) -> None:
        self.device = device
        self.ocr_service = ocr_service
        self.project_root = Path(project_root)
        self.routing_path = Path(routing_path)
        self.template_dir = Path(template_dir)
        self.screen = screen

    # ---------------------------------------------------------------- inputs
    def ocr(self) -> Any:
        """V2's own OCR, lazily built. Never the external tool's OCR."""
        if self.ocr_service is not None:
            return self.ocr_service
        from winter_agent_v2.ocr import OCRService, RapidOCRBackend

        self.ocr_service = OCRService(RapidOCRBackend())
        return self.ocr_service

    def capture(self, destination: Path) -> Path | None:
        """Grab a frame through the caller's device. Needs no lease of its own."""
        if self.device is None:
            return None
        destination.parent.mkdir(parents=True, exist_ok=True)
        return self.device.screenshot(destination)

    # ------------------------------------------------------------- step 1 & 2
    def tokens_for(self, frame: Path) -> list[Any]:
        """Every OCR token on one frame, read once.

        Harvesting asks the same frame about dozens of labels; running the
        recogniser once per label turns a page visit into minutes of repeat work
        and, worse, into several slightly different readings of one picture.
        """
        result = self.ocr().recognize(Path(frame))
        return list(getattr(result, "tokens", result) or [])

    def locate_in_tokens(self, tokens: list[Any], text: str) -> tuple[list[int], float, str] | None:
        """Highest-confidence token containing ``text``. Mirrors the tool's step 2.

        V2's ``OCRToken`` is a dataclass carrying ``confidence`` where the external
        tool's OCR backend carries ``score``, so both spellings are read -- the same
        tolerance that tool implements in its own ``_val`` helper, for the same
        reason: two different OCR backends, one comparison.
        """
        hits = []
        for token in tokens:
            seen = _field(token, "text")
            if seen and text in str(seen):
                hits.append(token)
        if not hits:
            return None

        def _conf(t: Any) -> float:
            value = _field(t, "score")
            if value is None:
                value = _field(t, "confidence")
            return float(value or 0.0)

        best = max(hits, key=_conf)
        box = normalize_box(_field(best, "box"))
        if box is None:
            return None
        return box, _conf(best), str(_field(best, "text") or "")

    def locate_text(self, frame: Path, text: str) -> tuple[list[int], float, str] | None:
        """One-shot convenience over :meth:`tokens_for` + :meth:`locate_in_tokens`."""
        return self.locate_in_tokens(self.tokens_for(frame), text)

    # ------------------------------------------------------------------ step 3
    def generate(self, request: GenerationRequest, *, frame: Path | None = None,
                 stamp: str | None = None) -> GeneratedNode | None:
        """Generate one node for one control. Returns ``None`` if the text is not on screen.

        Nothing here claims the node works: :meth:`validate` is what decides that.
        """
        if frame is None:
            stamp = stamp or datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
            frame = self.project_root / "dataset" / "raw" / "autogen" / f"{stamp}.png"
            got = self.capture(frame)
            if got is None:
                return None
            frame = got

        found = self.locate_text(frame, request.cn_text)
        if found is None:
            return None
        box, score, observed = found
        roi = compute_roi(box, request.expand, self.screen)

        warnings: list[str] = []
        if score < 0.9:
            warnings.append(f"OCR score {score:.4f} is below 0.9; the crop may be off")

        want = request.want
        evidence = {
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "source": "winter_agent_v2.pipeline_autogen (TOOL_SHAPED OCR node + V2_NATIVE template)",
            "frame": str(frame),
            "observed_text": observed,
            "observed_box": box,
            "ocr_score": round(score, 4),
            "expand": request.expand,
            "validation": "NONE",
        }

        if want == "ocr":
            routing = build_routing_ocr_node(request.cn_text, roi)
            return GeneratedNode(
                semantic=request.semantic, skill_id=request.skill_id, kind="OCR",
                routing_node=routing, pipeline_node=build_ocr_pipeline_node(request.cn_text, roi),
                observed_text=observed, observed_score=score, expansion=request.expand,
                frame=Path(frame), evidence=evidence, warnings=warnings,
            )

        template_path = self._crop(frame, roi, request.semantic, observed)
        if template_path is None:
            # No template could be cropped, so fall back to the text node the tool
            # would have produced rather than reporting a failure as success.
            warnings.append("template crop unavailable; falling back to OCR node")
            routing = build_routing_ocr_node(request.cn_text, roi)
            return GeneratedNode(
                semantic=request.semantic, skill_id=request.skill_id, kind="OCR",
                routing_node=routing, pipeline_node=build_ocr_pipeline_node(request.cn_text, roi),
                observed_text=observed, observed_score=score, expansion=request.expand,
                frame=Path(frame), evidence=evidence, warnings=warnings,
            )

        routing = build_routing_template_node(
            request.semantic, _relative(template_path, self.project_root), roi=roi,
        )
        return GeneratedNode(
            semantic=request.semantic, skill_id=request.skill_id, kind="TEMPLATE",
            routing_node=routing,
            pipeline_node=build_template_pipeline_node(request.semantic, roi),
            observed_text=observed, observed_score=score, expansion=request.expand,
            template_path=template_path, frame=Path(frame), evidence=evidence,
            warnings=warnings,
        )

    def _crop(self, frame: Path, roi: Sequence[int],
              semantic: str, observed: str) -> Path | None:
        """Crop the control out of the frame. V2_NATIVE — the tool has no image path.

        The rect cropped is the *clipped* ROI itself, not box+expand: MAA searches
        inside ``roi`` and rejects a template larger than that region (``templ size
        is too large``), so the two must come from the same rectangle. Near the
        screen edge ``compute_roi`` shrinks, and a crop that ignored that shrink
        produced templates no search region could ever hold.
        """
        try:
            from PIL import Image
        except Exception:
            return None
        left, top, width, height = (int(v) for v in roi)
        right, bottom = left + width, top + height
        digest = sha1(f"{semantic}|{observed}|{left},{top},{right},{bottom}".encode()).hexdigest()[:8]
        dest = self.template_dir / f"{semantic.lower()}__autogen_{digest}.png"
        try:
            dest.parent.mkdir(parents=True, exist_ok=True)
            with Image.open(frame) as im:
                im.convert("RGB").crop((left, top, right, bottom)).save(dest, "PNG")
        except Exception:
            return None
        return dest

    # ------------------------------------------------------------------ wiring
    def wire(self, node: GeneratedNode, *, migration_priority: str = "P3",
             note: str = "") -> tuple[bool, str]:
        """Persist a node into ``backend_routing.json`` so the router can reach it.

        Goes through ``RoutingTable.load``/``save`` rather than hand-editing the
        JSON, because the file also carries ``policy``, ``device`` and
        ``not_migrated``; rewriting it from our own idea of its shape would drop
        another session's unmerged work — the same class of mistake as the
        semantic-dictionary incident.
        """
        from winter_agent_v2.executor_router import RoutingTable

        table = RoutingTable.load(self.routing_path)
        if table.path is None:
            table.path = self.routing_path
        skills = dict(table.skills)
        entry = dict(skills.get(node.skill_id, {}))
        recognition = dict(entry.get("recognition", {}) or {})

        existed = node.semantic in recognition
        recognition[node.semantic] = node.routing_node

        entry["recognition"] = recognition
        entry.setdefault("preferred", "MAA")
        entry.setdefault("fallback", "ADB")
        entry["recognition_backend"] = "MAA"
        # A generated node is wired but NOT promoted: promotion means the corpus
        # gate (>=3 independent live positives, clean negatives) was met, and a
        # harvest-validated node has not earned that. The explicit flag keeps the
        # router's P0 invariant meaningful -- a node cannot drift into "promoted"
        # by an operator forgetting to change a priority letter.
        entry.setdefault("promoted", False)
        # An existing P0/P1 must not be demoted by an autogen write; only raise.
        current = str(entry.get("migration_priority", "P3"))
        entry["migration_priority"] = _higher_priority(current, migration_priority)
        if entry["migration_priority"] == "P0" and not entry.get("promoted", False):
            # Same rule from the other side: never let a priority bump imply a
            # promotion the evidence does not carry.
            entry["migration_priority"] = "P1"

        evidence = dict(entry.get("evidence", {}) or {})
        evidence.update({k: v for k, v in node.evidence.items()})
        evidence["autogen_node_count"] = len(recognition)
        if existed:
            evidence["autogen_overwritten_at"] = node.evidence.get("generated_at", "")
        if note:
            evidence["autogen_note"] = note
        entry["evidence"] = evidence

        skills[node.skill_id] = entry
        table.skills = skills
        table.save()
        return True, ("OVERWROTE" if existed else "CREATED")

    # ---------------------------------------------------------------- evidence
    def validate(self, node: GeneratedNode, *, positives: Sequence[Path],
                 negatives: Sequence[Path] = (), adapter: Any = None) -> dict[str, Any]:
        """Run a node against real frames. Nothing is promoted on generation alone."""
        report: dict[str, Any] = {
            "semantic": node.semantic, "skill_id": node.skill_id, "kind": node.kind,
            "positives": len(positives), "negatives": len(negatives),
            "positive_hits": 0, "negative_hits": 0, "errors": [], "corpus_sufficient": False,
        }
        if adapter is None:
            report["errors"].append("NO_ADAPTER")
            return report
        for frame in positives:
            hit, _err = self._try_match(adapter, node, Path(frame), expect_hit=True)
            report["positive_hits"] += int(hit)
        for frame in negatives:
            hit, _err = self._try_match(adapter, node, Path(frame), expect_hit=False)
            report["negative_hits"] += int(hit)
        report["corpus_sufficient"] = (
            len(positives) >= 3 and report["positive_hits"] == len(positives)
            and len(negatives) >= 3 and report["negative_hits"] == 0
        )
        return report

    def _try_match(self, adapter: Any, node: GeneratedNode, frame: Path,
                   expect_hit: bool) -> tuple[bool, str | None]:
        image = self._load_rgb(frame)
        if image is None:
            return False, f"FRAME_UNREADABLE:{frame.name}"
        try:
            if dispatch_hint(node.routing_node) == "OCR":
                results, err = adapter.ocr(
                    image, expected=list(node.routing_node.get("expected", [])),
                    roi=tuple(node.routing_node.get("roi", ()) ) or None,
                )
                if err:
                    return False, err
                return bool(results), None
            images = None
            source = node.routing_node.get("source_template")
            if source:
                src = Path(source)
                if not src.is_absolute():
                    src = self.project_root / src
                if src.is_file():
                    images = {str(node.routing_node.get("template", node.semantic)): src}
            out = adapter.find(
                # The frame is the point of the exercise: validation answers
                # "does this node find the control on THIS picture". Passing
                # ``None`` would make the adapter capture whatever it is looking
                # at right now, so every "positive" would be graded against an
                # unrelated screen and even a perfect template would read 0/1.
                image, node.semantic,
                template=str(node.routing_node.get("template", node.semantic)),
                roi=tuple(node.routing_node.get("roi")) if node.routing_node.get("roi") else None,
                threshold=node.routing_node.get("threshold", 0.7),
                images=images,
            )
            return bool(out.hit), out.error
        except Exception as exc:  # noqa: BLE001
            return False, f"{type(exc).__name__}:{exc}"

    def _load_rgb(self, frame: Path):
        """Read a PNG as the RGB array the adapter expects (``to_rgb_frame`` contract)."""
        try:
            import numpy as np
            from PIL import Image
            with Image.open(frame) as im:
                return np.asarray(im.convert("RGB"))
        except Exception:
            return None


def _relative(path: Path, root: Path) -> str:
    try:
        return str(Path(path).resolve().relative_to(Path(root).resolve())).replace("\\", "/")
    except ValueError:
        return str(path)


def _higher_priority(current: str, new: str) -> str:
    """Keep the more urgent of two priorities so autogen can never demote a node."""
    try:
        return current if int(current[1:]) <= int(new[1:]) else new
    except (ValueError, IndexError):
        return current
